<?php
// Banco de REACT (Reescrito Automáticamente)
function get_react_bank() {
    return array (
  0 => 
  array (
    'pregunta' => '¿Para qué sirve el hook useState en React?',
    'opcion_a' => 'Para agregar estado local a un componente funcional.',
    'opcion_b' => 'Para gestionar el estado global de toda la aplicación.',
    'opcion_c' => 'Para suscribirse a cambios en el DOM del navegador.',
    'opcion_d' => 'Para definir efectos secundarios después del renderizado.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'useState retorna [valor, setter]; al llamar setter React re-renderiza el componente.',
  ),
  1 => 
  array (
    'pregunta' => '¿Qué hace useEffect en componentes funcionales de React?',
    'opcion_a' => 'Ejecuta efectos secundarios después de que el componente ha renderizado.',
    'opcion_b' => 'Define variables de estado inmutables dentro del componente.',
    'opcion_c' => 'Transforma funciones síncronas en procesos asíncronos automáticamente.',
    'opcion_d' => 'Compila JSX a código binario antes de que el navegador procese el DOM.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'useEffect ejecuta suscripciones, timers y llamadas a APIs tras la actualización del DOM.',
  ),
  2 => 
  array (
    'pregunta' => '¿Cuál es la diferencia entre un componente controlado y uno no controlado?',
    'opcion_a' => 'Controlado: el estado del input lo maneja React. No controlado: lo maneja el DOM.',
    'opcion_b' => 'Controlado: solo acepta props. No controlado: usa estado interno sin props.',
    'opcion_c' => 'Controlado: se renderiza en el servidor. No controlado: solo en el cliente.',
    'opcion_d' => 'No hay diferencia funcional; es solo una convención de nomenclatura.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'En inputs controlados React es la fuente de verdad; en no controlados se usa useRef.',
  ),
  3 => 
  array (
    'pregunta' => '¿Para qué se usa el hook useRef en React?',
    'opcion_a' => 'Para mantener una referencia mutable que no dispara re-renderizados.',
    'opcion_b' => 'Para crear una copia del estado global accesible desde cualquier componente.',
    'opcion_c' => 'Para definir efectos secundarios con limpieza automática en el desmontaje.',
    'opcion_d' => 'Para memorizar el resultado de funciones puras entre renderizados.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'useRef.current persiste entre renders sin causar re-render; ideal para referencias al DOM.',
  ),
  4 => 
  array (
    'pregunta' => '¿Para qué sirve el hook useContext en React?',
    'opcion_a' => 'Para consumir valores de un Context sin necesidad de pasar props manualmente.',
    'opcion_b' => 'Para crear un contexto de ejecución asíncrono en el componente.',
    'opcion_c' => 'Para leer el contexto del navegador como idioma, zona horaria o resolución.',
    'opcion_d' => 'Para acceder al contexto de errores y capturar excepciones del árbol.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'useContext(MiContexto) retorna el valor actual del proveedor más cercano en el árbol.',
  ),
  5 => 
  array (
    'pregunta' => '¿Qué hace React.StrictMode en una aplicación React?',
    'opcion_a' => 'Activa advertencias adicionales y detecta efectos secundarios inesperados.',
    'opcion_b' => 'Impide que los usuarios inspeccionen el código fuente con DevTools.',
    'opcion_c' => 'Fuerza que todos los componentes sean de tipo función (no clases).',
    'opcion_d' => 'Activa el modo de producción con optimizaciones de rendimiento máximas.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'StrictMode ejecuta efectos dos veces en desarrollo para detectar dependencias ocultas.',
  ),
  6 => 
  array (
    'pregunta' => '¿Para qué sirve el archivo package.json en un proyecto React?',
    'opcion_a' => 'Define metadatos, dependencias y scripts del proyecto Node.js/React.',
    'opcion_b' => 'Almacena el estado global de la aplicación en formato JSON.',
    'opcion_c' => 'Configura las rutas de la aplicación para React Router.',
    'opcion_d' => 'Define los componentes globales registrados en la aplicación.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'package.json tiene dependencies, devDependencies y scripts como start, build y test.',
  ),
  7 => 
  array (
    'pregunta' => '¿Qué hace el operador && en el renderizado condicional de React?',
    'opcion_a' => 'Renderiza el elemento del lado derecho solo si la condición izquierda es verdadera.',
    'opcion_b' => 'Aplica estilos CSS condicionalmente al elemento según el estado del componente.',
    'opcion_c' => 'Combina dos componentes en uno solo sin agregar nodos extra al DOM.',
    'opcion_d' => 'Verifica que ambos props sean válidos antes de renderizar el componente.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => '{condicion && <Componente />} es el shorthand más común para renderizado condicional.',
  ),
  8 => 
  array (
    'pregunta' => '¿Qué hace el evento onSubmit en un formulario React?',
    'opcion_a' => 'Maneja el envío del formulario; se llama a e.preventDefault() para evitar recarga.',
    'opcion_b' => 'Valida automáticamente todos los campos del formulario en HTML5.',
    'opcion_c' => 'Envía los datos del formulario directamente a la URL definida en action.',
    'opcion_d' => 'Resetea todos los valores del formulario al estado inicial registrado.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'e.preventDefault() en onSubmit evita la recarga; luego se procesan los datos del estado.',
  ),
  9 => 
  array (
    'pregunta' => '¿Qué hace el spread operator {...props} en JSX?',
    'opcion_a' => 'Pasa todas las propiedades de un objeto como props al componente hijo.',
    'opcion_b' => 'Fusiona el estado actual del padre con las props del componente hijo.',
    'opcion_c' => 'Extiende el componente con funcionalidades adicionales del HOC padre.',
    'opcion_d' => 'Copia el árbol DOM del componente a un nuevo nodo en la página.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => '<Componente {...datos} /> equivale a <Componente a={datos.a} b={datos.b} ... />.',
  ),
  10 => 
  array (
    'pregunta' => '¿Cuándo deberías usar useReducer en lugar de useState?',
    'opcion_a' => 'Cuando el estado tiene lógica compleja con múltiples transiciones relacionadas.',
    'opcion_b' => 'Cuando el componente necesita compartir estado con componentes hermanos.',
    'opcion_c' => 'Cuando el estado es un string simple que cambia con frecuencia.',
    'opcion_d' => 'Cuando se necesita que el estado persista tras recargar la página.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'useReducer(reducer, state) centraliza la lógica de actualización de estado complejo.',
  ),
  11 => 
  array (
    'pregunta' => '¿Qué es el Context API en React y cuándo se usa?',
    'opcion_a' => 'Permite compartir datos entre componentes sin pasar props en cada nivel.',
    'opcion_b' => 'Expone la API del navegador para acceder a la cámara y el micrófono.',
    'opcion_c' => 'Gestiona las llamadas HTTP del componente con cache automática.',
    'opcion_d' => 'Define los endpoints de la API REST que el componente va a consumir.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Context evita "prop drilling"; ideal para tema, idioma o usuario autenticado global.',
  ),
  12 => 
  array (
    'pregunta' => '¿Qué hace React.memo() y cuándo conviene usarlo?',
    'opcion_a' => 'HOC que evita re-renderizar un componente si sus props no cambiaron.',
    'opcion_b' => 'Almacena el resultado de las peticiones HTTP del componente en memoria.',
    'opcion_c' => 'Memoriza el árbol DOM del componente para animaciones más fluidas.',
    'opcion_d' => 'Crea una copia inmutable del estado para comparaciones de rendimiento.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'memo() hace shallow comparison de props; úsalo en componentes puros con renders costosos.',
  ),
  13 => 
  array (
    'pregunta' => '¿Qué es React Router y cómo se implementa la navegación básica?',
    'opcion_a' => 'Librería de enrutamiento; se usa <BrowserRouter>, <Routes> y <Route path>.',
    'opcion_b' => 'Sistema de routing integrado en React que no requiere instalación adicional.',
    'opcion_c' => 'Plugin de Vite que genera rutas automáticamente basadas en el filesystem.',
    'opcion_d' => 'HOC que envuelve la app e inyecta el objeto history en todos los hijos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'react-router-dom v6 usa <Routes><Route path="/home" element={<Home />} /></Routes>.',
  ),
  14 => 
  array (
    'pregunta' => '¿Cuándo se usa useLayoutEffect en lugar de useEffect?',
    'opcion_a' => 'Cuando se necesita leer o mutar el DOM antes de que el navegador pinte la pantalla.',
    'opcion_b' => 'Cuando el efecto debe ejecutarse antes del primer renderizado del componente.',
    'opcion_c' => 'Cuando el efecto depende del layout CSS calculado por el navegador.',
    'opcion_d' => 'Siempre que se hagan peticiones HTTP para evitar estados de carga visibles.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'useLayoutEffect es síncrono tras mutaciones DOM; evita parpadeos al leer dimensiones.',
  ),
  15 => 
  array (
    'pregunta' => '¿Qué es el "prop drilling" y cómo se soluciona en React?',
    'opcion_a' => 'Pasar props por muchos niveles sin que los intermedios las usen; se resuelve con Context.',
    'opcion_b' => 'Usar demasiadas props en un componente; se resuelve con useReducer.',
    'opcion_c' => 'Pasar funciones como props que modifican el estado del componente padre.',
    'opcion_d' => 'Renderizar props que contienen otros componentes en lugar de datos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Context API, Zustand o Redux eliminan prop drilling sin pasar por componentes intermedios.',
  ),
  16 => 
  array (
    'pregunta' => '¿Qué hace forwardRef en React?',
    'opcion_a' => 'Permite que un componente funcional acepte y reenvíe una ref al DOM interno.',
    'opcion_b' => 'Reenvía props de un componente padre a todos sus descendientes automáticamente.',
    'opcion_c' => 'Propaga los eventos del componente hijo hacia el componente padre.',
    'opcion_d' => 'Crea referencias compartidas entre componentes en diferentes árboles React.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'forwardRef(fn) permite ref.current apuntar al elemento DOM interno del componente hijo.',
  ),
  17 => 
  array (
    'pregunta' => '¿Qué es el patrón "render props" en React?',
    'opcion_a' => 'Una prop que es una función y define qué renderizar con datos del componente.',
    'opcion_b' => 'Un conjunto de props que controlan qué parte del componente se renderiza.',
    'opcion_c' => 'Las props que React genera automáticamente al renderizar un componente.',
    'opcion_d' => 'Un patrón donde el padre inyecta componentes renderizados en el hijo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '<Tracker render={(data) => <Display data={data} />} /> es el patrón render props clásico.',
  ),
  18 => 
  array (
    'pregunta' => '¿Cuál es la diferencia entre SPA (Single Page App) y SSR (Server Side Render)?',
    'opcion_a' => 'SPA renderiza en el cliente; SSR genera el HTML en el servidor antes de enviar.',
    'opcion_b' => 'SPA usa múltiples páginas HTML; SSR usa una sola página con React.',
    'opcion_c' => 'SSR es más lento para el usuario final porque el servidor hace más trabajo.',
    'opcion_d' => 'SPA solo funciona con React; SSR solo funciona con Next.js o Remix.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'SSR mejora el FCP y SEO; SPA es más interactiva pero tiene TTFB más alto en primera carga.',
  ),
  19 => 
  array (
    'pregunta' => '¿Qué es Next.js y qué agrega sobre React puro?',
    'opcion_a' => 'Framework React con SSR, SSG, file-based routing, API routes y optimizaciones.',
    'opcion_b' => 'Una versión de React optimizada para dispositivos móviles y PWA.',
    'opcion_c' => 'Un framework CSS integrado con React que reemplaza Tailwind y styled-components.',
    'opcion_d' => 'Un gestor de estado avanzado que reemplaza Redux en proyectos grandes.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Next.js ofrece App Router, RSC, image optimization, fonts y API routes integradas.',
  ),
  20 => 
  array (
    'pregunta' => '¿Cómo se implementa la paginación infinita con React Query?',
    'opcion_a' => 'Con useInfiniteQuery que gestiona páginas, hasNextPage y fetchNextPage.',
    'opcion_b' => 'Con useQuery paginada llamando a setPage en un useEffect con IntersectionObserver.',
    'opcion_c' => 'Con usePagination de React Query que acumula los resultados de cada página.',
    'opcion_d' => 'Con un estado local y useEffect que detecta el scroll al final de la lista.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'useInfiniteQuery(key, fn, { getNextPageParam }) acumula páginas y expone fetchNextPage.',
  ),
  21 => 
  array (
    'pregunta' => '¿Qué es el patrón "Optimistic UI" y cómo se implementa con React Query?',
    'opcion_a' => 'Actualizar el UI inmediatamente antes de confirmar la respuesta del servidor.',
    'opcion_b' => 'Mostrar un spinner optimista mientras la respuesta del servidor llega.',
    'opcion_c' => 'Cachear las respuestas del servidor para mostrarlas sin conexión a internet.',
    'opcion_d' => 'Predecir qué datos solicitará el usuario y pre-cargarlos en background.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'useMutation con onMutate actualiza el cache; onError revierte si el servidor falla.',
  ),
  22 => 
  array (
    'pregunta' => '¿Qué son los Error Boundaries en React y cómo se implementan?',
    'opcion_a' => 'Componentes de clase con componentDidCatch que capturan errores en hijos.',
    'opcion_b' => 'Hooks especiales que capturan excepciones en cualquier componente funcional.',
    'opcion_c' => 'Bloques try/catch globales que React inyecta automáticamente en el árbol.',
    'opcion_d' => 'Middlewares de Redux que interceptan errores en las acciones dispatched.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Solo los componentes de clase pueden ser Error Boundaries vía getDerivedStateFromError.',
  ),
  23 => 
  array (
    'pregunta' => '¿Qué técnica de performance usa React al ejecutar múltiples setState juntos?',
    'opcion_a' => 'Batching: agrupa múltiples actualizaciones en un solo re-renderizado.',
    'opcion_b' => 'Debouncing: espera un tiempo antes de procesar la última actualización.',
    'opcion_c' => 'Throttling: limita a una actualización por intervalo de tiempo definido.',
    'opcion_d' => 'Memoization: cachea el estado anterior para compararlo con el nuevo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'React 18 hace automatic batching incluso en promesas y timeouts, reduciendo re-renders.',
  ),
  24 => 
  array (
    'pregunta' => '¿Qué es el patrón "compound components" en React?',
    'opcion_a' => 'Componentes relacionados que comparten estado implícito via Context internamente.',
    'opcion_b' => 'Componentes que se compilan juntos en un único bundle de producción.',
    'opcion_c' => 'Componentes que heredan de una clase base compartida con estado común.',
    'opcion_d' => 'Componentes que combinan múltiples hooks personalizados en uno solo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Ejemplo: <Select><Select.Option/></Select> donde ambos comparten estado sin prop drilling.',
  ),
  25 => 
  array (
    'pregunta' => '¿Cuáles son las métricas Core Web Vitals relevantes para apps React?',
    'opcion_a' => 'LCP (carga), FID/INP (interactividad) y CLS (estabilidad visual).',
    'opcion_b' => 'TTI (tiempo de interactividad), FMP (primera pintura) y TBT (bloqueo).',
    'opcion_c' => 'TTFB (tiempo primer byte), FCP (primer contenido) y SI (speed index).',
    'opcion_d' => 'Bundle size, número de re-renders y tiempo de hidratación del HTML.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'LCP, INP (antes FID) y CLS son las métricas de Google que afectan el ranking SEO real.',
  ),
  26 => 
  array (
    'pregunta' => '¿Cómo funciona el Server-Side Rendering de Next.js con getServerSideProps?',
    'opcion_a' => 'Ejecuta en cada request: fetches datos en servidor y los pasa como props a la página.',
    'opcion_b' => 'Genera HTML estático en build-time y lo sirve desde CDN sin servidor.',
    'opcion_c' => 'Pre-renderiza solo la estructura HTML y los datos los carga el cliente.',
    'opcion_d' => 'Ejecuta una sola vez en el arranque del servidor y cachea el resultado.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'getServerSideProps corre por cada request (SSR); getStaticProps corre en build (SSG).',
  ),
  27 => 
  array (
    'pregunta' => '¿Qué son los React DevTools y qué información permiten ver?',
    'opcion_a' => 'Extensión del navegador para inspeccionar el árbol de componentes, props y estado.',
    'opcion_b' => 'Herramientas de línea de comandos para analizar el bundle de producción.',
    'opcion_c' => 'Plugin de VS Code para debuggear componentes React sin navegador.',
    'opcion_d' => 'Panel en el servidor para monitorear renders remotos en producción.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'React DevTools muestra el árbol, props, hooks, estado y el Profiler para medir renders.',
  ),
  28 => 
  array (
    'pregunta' => '¿Qué son las "islands architecture" (islas) y cómo se relaciona con React?',
    'opcion_a' => 'HTML estático con "islas" de interactividad React; reduce el JS enviado al cliente.',
    'opcion_b' => 'Componentes React aislados que no pueden comunicarse con otros componentes.',
    'opcion_c' => 'Módulos de React que se ejecutan en servidores distribuidos geográficamente.',
    'opcion_d' => 'Fragmentos del bundle que solo se cargan cuando el usuario los solicita.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Frameworks como Astro usan islas; solo los componentes interactivos envían JS al browser.',
  ),
  29 => 
  array (
    'pregunta' => '¿Qué problema resuelve el patrón "state machine" con XState en React?',
    'opcion_a' => 'Gestiona estados finitos complejos eliminando lógica condicional dispersa.',
    'opcion_b' => 'Persiste el estado del componente en una máquina de estados del servidor.',
    'opcion_c' => 'Optimiza el rendimiento de componentes con muchas transiciones de estado.',
    'opcion_d' => 'Sincroniza el estado entre múltiples instancias de React en tabs distintas.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'XState modela flujos como: idle→loading→success|error; elimina bugs de estados imposibles.',
  ),
  30 => 
  array (
    'pregunta' => '¿Qué hook maneja el estado local?',
    'opcion_a' => 'useState',
    'opcion_b' => 'useEffect',
    'opcion_c' => 'useRef',
    'opcion_d' => 'useMemo',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'useState crea estado local.',
  ),
  31 => 
  array (
    'pregunta' => '¿Qué hook ejecuta efectos secundarios?',
    'opcion_a' => 'useState',
    'opcion_b' => 'useEffect',
    'opcion_c' => 'useRef',
    'opcion_d' => 'useMemo',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'useEffect maneja efectos secundarios.',
  ),
  32 => 
  array (
    'pregunta' => '¿Qué método de ciclo de vida equivale a useEffect con array vacío?',
    'opcion_a' => 'componentDidMount',
    'opcion_b' => 'render',
    'opcion_c' => 'componentWillUnmount',
    'opcion_d' => 'constructor',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'componentDidMount se ejecuta una vez.',
  ),
  33 => 
  array (
    'pregunta' => '¿Qué prop especial permite renderizar elementos hijos?',
    'opcion_a' => 'children',
    'opcion_b' => 'props',
    'opcion_c' => 'elements',
    'opcion_d' => 'nodes',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'La prop children pasa componentes hijos.',
  ),
  34 => 
  array (
    'pregunta' => '¿Cómo se actualiza el estado basado en el estado anterior?',
    'opcion_a' => 'setState(prev => prev + 1)',
    'opcion_b' => 'setState(state + 1)',
    'opcion_c' => 'state = state + 1',
    'opcion_d' => 'this.state++',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Se usa una función callback en setState.',
  ),
  35 => 
  array (
    'pregunta' => '¿Qué hook memoriza un valor calculado?',
    'opcion_a' => 'useMemo',
    'opcion_b' => 'useCallback',
    'opcion_c' => 'useRef',
    'opcion_d' => 'useState',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'useMemo cachea valores calculados.',
  ),
  36 => 
  array (
    'pregunta' => '¿Qué hook memoriza una función?',
    'opcion_a' => 'useMemo',
    'opcion_b' => 'useCallback',
    'opcion_c' => 'useRef',
    'opcion_d' => 'useEffect',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => 'useCallback cachea referencias a funciones.',
  ),
  37 => 
  array (
    'pregunta' => '¿Qué herramienta empaqueta aplicaciones React?',
    'opcion_a' => 'Webpack',
    'opcion_b' => 'Babel',
    'opcion_c' => 'ESLint',
    'opcion_d' => 'Prettier',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Webpack es un bundler de módulos.',
  ),
  38 => 
  array (
    'pregunta' => '¿Qué compilador transforma JSX en JavaScript?',
    'opcion_a' => 'Babel',
    'opcion_b' => 'Webpack',
    'opcion_c' => 'NPM',
    'opcion_d' => 'Node',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Babel transpila JSX a JS estándar.',
  ),
  39 => 
  array (
    'pregunta' => '¿Qué biblioteca maneja rutas en React?',
    'opcion_a' => 'React Router',
    'opcion_b' => 'Redux',
    'opcion_c' => 'Axios',
    'opcion_d' => 'Next.js',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'React Router gestiona la navegación.',
  ),
  40 => 
  array (
    'pregunta' => '¿Qué estado global es muy popular en React?',
    'opcion_a' => 'Redux',
    'opcion_b' => 'Axios',
    'opcion_c' => 'Jest',
    'opcion_d' => 'Enzyme',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Redux maneja el estado global complejo.',
  ),
  41 => 
  array (
    'pregunta' => '¿Qué atributo JSX reemplaza a class de HTML?',
    'opcion_a' => 'className',
    'opcion_b' => 'class',
    'opcion_c' => 'css',
    'opcion_d' => 'style',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'className se usa para evitar conflictos con JS.',
  ),
  42 => 
  array (
    'pregunta' => '¿Qué atributo JSX reemplaza a for de HTML?',
    'opcion_a' => 'htmlFor',
    'opcion_b' => 'for',
    'opcion_c' => 'labelFor',
    'opcion_d' => 'id',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'htmlFor se usa en lugar de for.',
  ),
  43 => 
  array (
    'pregunta' => '¿Qué hook permite referenciar un elemento del DOM?',
    'opcion_a' => 'useRef',
    'opcion_b' => 'useState',
    'opcion_c' => 'useEffect',
    'opcion_d' => 'useDOM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'useRef guarda referencias mutables.',
  ),
  44 => 
  array (
    'pregunta' => '¿Qué componente de React Router envuelve toda la app?',
    'opcion_a' => 'BrowserRouter',
    'opcion_b' => 'Route',
    'opcion_c' => 'Link',
    'opcion_d' => 'Switch',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'BrowserRouter provee el contexto de rutas.',
  ),
  45 => 
  array (
    'pregunta' => '¿Cómo se llama el DOM virtual en React?',
    'opcion_a' => 'Virtual DOM',
    'opcion_b' => 'Shadow DOM',
    'opcion_c' => 'Real DOM',
    'opcion_d' => 'Document',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'React usa el Virtual DOM para optimizar.',
  ),
  46 => 
  array (
    'pregunta' => '¿Qué función compara el Virtual DOM con el real?',
    'opcion_a' => 'Reconciliation',
    'opcion_b' => 'Diffing',
    'opcion_c' => 'Rendering',
    'opcion_d' => 'Mounting',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'El proceso se llama Reconciliación.',
  ),
  47 => 
  array (
    'pregunta' => '¿Qué biblioteca se usa comúnmente para peticiones HTTP?',
    'opcion_a' => 'Axios',
    'opcion_b' => 'Redux',
    'opcion_c' => 'Lodash',
    'opcion_d' => 'Moment',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Axios es un cliente HTTP basado en promesas.',
  ),
  48 => 
  array (
    'pregunta' => '¿Qué framework usa React para SSR?',
    'opcion_a' => 'Next.js',
    'opcion_b' => 'Create React App',
    'opcion_c' => 'Gatsby',
    'opcion_d' => 'Vite',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Next.js permite renderizado en servidor.',
  ),
  49 => 
  array (
    'pregunta' => '¿Qué comando inicia una app con Vite?',
    'opcion_a' => 'npm create vite@latest',
    'opcion_b' => 'npx create-react-app',
    'opcion_c' => 'npm start',
    'opcion_d' => 'vite run',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Vite es muy rápido para inicializar.',
  ),
  50 => 
  array (
    'pregunta' => '¿Qué atributo es obligatorio al iterar listas en JSX?',
    'opcion_a' => 'key',
    'opcion_b' => 'id',
    'opcion_c' => 'index',
    'opcion_d' => 'ref',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'La key ayuda a React a identificar elementos.',
  ),
  51 => 
  array (
    'pregunta' => '¿Qué hook se usa para suscribirse a un Contexto?',
    'opcion_a' => 'useContext',
    'opcion_b' => 'useState',
    'opcion_c' => 'useProvider',
    'opcion_d' => 'useReducer',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'useContext lee valores de un Provider.',
  ),
  52 => 
  array (
    'pregunta' => '¿Qué hook es una alternativa a useState para lógica compleja?',
    'opcion_a' => 'useReducer',
    'opcion_b' => 'useEffect',
    'opcion_c' => 'useMemo',
    'opcion_d' => 'useContext',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'useReducer maneja estados con acciones.',
  ),
  53 => 
  array (
    'pregunta' => '¿Qué patrón renderiza props como funciones?',
    'opcion_a' => 'Render Props',
    'opcion_b' => 'HOC',
    'opcion_c' => 'Hooks',
    'opcion_d' => 'Context',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Render Props inyecta datos dinámicos.',
  ),
  54 => 
  array (
    'pregunta' => '¿Qué sigla significa Componente de Orden Superior?',
    'opcion_a' => 'HOC',
    'opcion_b' => 'JSX',
    'opcion_c' => 'DOM',
    'opcion_d' => 'SSR',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Higher-Order Component envuelve componentes.',
  ),
  55 => 
  array (
    'pregunta' => '¿Qué etiqueta permite fragments sin importar React.Fragment?',
    'opcion_a' => '<></>',
    'opcion_b' => '<fragment>',
    'opcion_c' => '<temp>',
    'opcion_d' => '<div>',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Sintaxis corta para fragmentos.',
  ),
  56 => 
  array (
    'pregunta' => '¿Qué hook se introdujo para manejar IDs únicos?',
    'opcion_a' => 'useId',
    'opcion_b' => 'useRef',
    'opcion_c' => 'useUnique',
    'opcion_d' => 'useKey',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'useId genera IDs estables (React 18).',
  ),
  57 => 
  array (
    'pregunta' => '¿Qué función suspende el renderizado hasta que los datos carguen?',
    'opcion_a' => 'Suspense',
    'opcion_b' => 'Lazy',
    'opcion_c' => 'Await',
    'opcion_d' => 'Defer',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Suspense muestra un fallback temporal.',
  ),
  58 => 
  array (
    'pregunta' => '¿Qué función carga componentes dinámicamente?',
    'opcion_a' => 'React.lazy',
    'opcion_b' => 'import',
    'opcion_c' => 'dynamic',
    'opcion_d' => 'Suspense',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'lazy() permite code-splitting.',
  ),
  59 => 
  array (
    'pregunta' => '¿Qué prop de Suspense define el contenido temporal?',
    'opcion_a' => 'fallback',
    'opcion_b' => 'loading',
    'opcion_c' => 'placeholder',
    'opcion_d' => 'spinner',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'fallback muestra la interfaz de carga.',
  ),
  60 => 
  array (
    'pregunta' => '¿Qué característica de React 18 agrupa actualizaciones de estado?',
    'opcion_a' => 'Automatic Batching',
    'opcion_b' => 'Concurrency',
    'opcion_c' => 'Suspense',
    'opcion_d' => 'Transitions',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'El batching reduce los re-renders.',
  ),
  61 => 
  array (
    'pregunta' => '¿Qué hook de React 18 marca actualizaciones como no urgentes?',
    'opcion_a' => 'useTransition',
    'opcion_b' => 'useDeferredValue',
    'opcion_c' => 'useMemo',
    'opcion_d' => 'useIdle',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'useTransition prioriza el renderizado.',
  ),
  62 => 
  array (
    'pregunta' => '¿Qué hook retrasa la actualización de un valor?',
    'opcion_a' => 'useDeferredValue',
    'opcion_b' => 'useTransition',
    'opcion_c' => 'useMemo',
    'opcion_d' => 'useRef',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'useDeferredValue permite render fluido.',
  ),
  63 => 
  array (
    'pregunta' => '¿Qué función de prueba viene por defecto en CRA?',
    'opcion_a' => 'Jest',
    'opcion_b' => 'Mocha',
    'opcion_c' => 'Cypress',
    'opcion_d' => 'Puppeteer',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Jest es el test runner predeterminado.',
  ),
  64 => 
  array (
    'pregunta' => '¿Qué librería prueba componentes React de forma accesible?',
    'opcion_a' => 'React Testing Library',
    'opcion_b' => 'Enzyme',
    'opcion_c' => 'Selenium',
    'opcion_d' => 'Jest',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'RTL fomenta probar como un usuario real.',
  ),
  65 => 
  array (
    'pregunta' => '¿Qué hook permite insertar lógica antes de pintar la pantalla?',
    'opcion_a' => 'useLayoutEffect',
    'opcion_b' => 'useEffect',
    'opcion_c' => 'usePaint',
    'opcion_d' => 'useRender',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'useLayoutEffect es síncrono tras mutar el DOM.',
  ),
  66 => 
  array (
    'pregunta' => '¿Qué componente estricto de React avisa sobre código legado?',
    'opcion_a' => 'StrictMode',
    'opcion_b' => 'DebugMode',
    'opcion_c' => 'SafeMode',
    'opcion_d' => 'Profiler',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'StrictMode resalta problemas potenciales.',
  ),
  67 => 
  array (
    'pregunta' => '¿Qué API mide el rendimiento de renderizado?',
    'opcion_a' => 'Profiler',
    'opcion_b' => 'Performance',
    'opcion_c' => 'Trace',
    'opcion_d' => 'Profiler API',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'React Profiler mide tiempos de renderizado.',
  ),
  68 => 
  array (
    'pregunta' => '¿Cómo se evita que un componente funcional se re-renderice?',
    'opcion_a' => 'React.memo',
    'opcion_b' => 'useMemo',
    'opcion_c' => 'PureComponent',
    'opcion_d' => 'shouldUpdate',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'memo() hace una comparación superficial de props.',
  ),
  69 => 
  array (
    'pregunta' => '¿Qué librería permite escribir CSS en JS?',
    'opcion_a' => 'Styled Components',
    'opcion_b' => 'Sass',
    'opcion_c' => 'Less',
    'opcion_d' => 'CSS Modules',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Styled Components usa template literals para CSS.',
  ),
  70 => 
  array (
    'pregunta' => '¿Qué framework estático basado en React es respaldado por Vercel?',
    'opcion_a' => 'Next.js',
    'opcion_b' => 'Gatsby',
    'opcion_c' => 'Astro',
    'opcion_d' => 'Remix',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Next.js es creado por Vercel.',
  ),
  71 => 
  array (
    'pregunta' => '¿Qué herramienta sustituye a Webpack en Vite?',
    'opcion_a' => 'Rollup',
    'opcion_b' => 'Parcel',
    'opcion_c' => 'Esbuild',
    'opcion_d' => 'Babel',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Vite usa Rollup para producción.',
  ),
  72 => 
  array (
    'pregunta' => '¿Qué librería facilita formularios complejos en React?',
    'opcion_a' => 'React Hook Form',
    'opcion_b' => 'Formik',
    'opcion_c' => 'Redux Form',
    'opcion_d' => 'Final Form',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'React Hook Form reduce re-renders en inputs.',
  ),
  73 => 
  array (
    'pregunta' => '¿Qué librería gestiona animaciones fluidas en React?',
    'opcion_a' => 'Framer Motion',
    'opcion_b' => 'React Transition',
    'opcion_c' => 'Anime.js',
    'opcion_d' => 'GSAP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Framer Motion es muy popular para animaciones.',
  ),
  74 => 
  array (
    'pregunta' => '¿Qué sistema de diseño de componentes es de Google?',
    'opcion_a' => 'MUI (Material UI)',
    'opcion_b' => 'Ant Design',
    'opcion_c' => 'Chakra UI',
    'opcion_d' => 'Bootstrap',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'MUI implementa Material Design en React.',
  ),
  75 => 
  array (
    'pregunta' => '¿Qué patrón divide código para carga diferida?',
    'opcion_a' => 'Code Splitting',
    'opcion_b' => 'Lazy Loading',
    'opcion_c' => 'Dynamic Import',
    'opcion_d' => 'Tree Shaking',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Code splitting reduce el bundle inicial.',
  ),
  76 => 
  array (
    'pregunta' => '¿Qué técnica elimina código no utilizado del bundle?',
    'opcion_a' => 'Tree Shaking',
    'opcion_b' => 'Minification',
    'opcion_c' => 'Uglify',
    'opcion_d' => 'Compressing',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Tree shaking limpia exportaciones muertas.',
  ),
  77 => 
  array (
    'pregunta' => '¿Qué es un componente que no maneja estado propio?',
    'opcion_a' => 'Stateless Component',
    'opcion_b' => 'Pure Component',
    'opcion_c' => 'Dumb Component',
    'opcion_d' => 'UI Component',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'También llamado componente presentacional.',
  ),
  78 => 
  array (
    'pregunta' => '¿Qué es un componente que gestiona lógica y estado?',
    'opcion_a' => 'Stateful Component',
    'opcion_b' => 'Smart Component',
    'opcion_c' => 'Container',
    'opcion_d' => 'Root',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'También conocido como componente contenedor.',
  ),
  79 => 
  array (
    'pregunta' => '¿Qué valor retorna useState por defecto si no se pasa argumento?',
    'opcion_a' => 'undefined',
    'opcion_b' => 'null',
    'opcion_c' => 'false',
    'opcion_d' => '0',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'El estado inicial es undefined.',
  ),
  80 => 
  array (
    'pregunta' => '¿Se pueden usar Hooks dentro de bucles o condicionales?',
    'opcion_a' => 'No',
    'opcion_b' => 'Sí',
    'opcion_c' => 'Depende',
    'opcion_d' => 'Solo useEffect',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Rompe las reglas de los Hooks.',
  ),
  81 => 
  array (
    'pregunta' => '¿Qué archivo de Next.js define las rutas de API?',
    'opcion_a' => 'api/route.js',
    'opcion_b' => 'server.js',
    'opcion_c' => 'pages/api',
    'opcion_d' => 'routes.js',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'App Router usa route.js para APIs.',
  ),
  82 => 
  array (
    'pregunta' => '¿Qué convención usa Next.js para rutas anidadas?',
    'opcion_a' => 'Carpetas',
    'opcion_b' => 'Archivos',
    'opcion_c' => 'Configuración',
    'opcion_d' => 'Decoradores',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'La estructura de carpetas define las rutas.',
  ),
  83 => 
  array (
    'pregunta' => '¿Qué es JSX?',
    'opcion_a' => 'Sintaxis de extensión JS',
    'opcion_b' => 'Un motor de plantillas',
    'opcion_c' => 'HTML estricto',
    'opcion_d' => 'Un lenguaje compilado',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'JSX extiende JS con sintaxis XML.',
  ),
  84 => 
  array (
    'pregunta' => '¿Qué método vinculaba this en componentes de clase?',
    'opcion_a' => 'bind()',
    'opcion_b' => 'call()',
    'opcion_c' => 'apply()',
    'opcion_d' => 'link()',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Se usaba bind en el constructor para eventos.',
  ),
  85 => 
  array (
    'pregunta' => '¿Qué función define prop types en React legado?',
    'opcion_a' => 'PropTypes',
    'opcion_b' => 'TypeScript',
    'opcion_c' => 'Flow',
    'opcion_d' => 'Interfaces',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'PropTypes validaba tipos en tiempo de ejecución.',
  ),
  86 => 
  array (
    'pregunta' => '¿Qué librería se usa para tipado estático en React actual?',
    'opcion_a' => 'TypeScript',
    'opcion_b' => 'Flow',
    'opcion_c' => 'PropTypes',
    'opcion_d' => 'JSDoc',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'TypeScript es el estándar moderno.',
  ),
  87 => 
  array (
    'pregunta' => '¿Qué propiedad CSS se escribe como backgroundColor en JSX?',
    'opcion_a' => 'background-color',
    'opcion_b' => 'bgcolor',
    'opcion_c' => 'background',
    'opcion_d' => 'color',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'JSX usa camelCase para propiedades CSS.',
  ),
  88 => 
  array (
    'pregunta' => '¿Cómo se envían datos del hijo al padre en React?',
    'opcion_a' => 'Callbacks en props',
    'opcion_b' => 'Event Emitters',
    'opcion_c' => 'Redux',
    'opcion_d' => 'Context',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'El padre pasa una función callback como prop.',
  ),
  89 => 
  array (
    'pregunta' => '¿Qué librería maneja estado del servidor y caché?',
    'opcion_a' => 'React Query',
    'opcion_b' => 'Redux',
    'opcion_c' => 'Zustand',
    'opcion_d' => 'Context API',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'React Query gestiona el estado asíncrono remoto.',
  ),
  90 => 
  array (
    'pregunta' => '¿Qué estado maneja Zustand?',
    'opcion_a' => 'Estado global simple',
    'opcion_b' => 'Estado del servidor',
    'opcion_c' => 'Rutas',
    'opcion_d' => 'Formularios',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Zustand es un gestor de estado ligero.',
  ),
  91 => 
  array (
    'pregunta' => '¿Qué librería moderna compite con Redux por simplicidad?',
    'opcion_a' => 'Zustand',
    'opcion_b' => 'MobX',
    'opcion_c' => 'Recoil',
    'opcion_d' => 'Jotai',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Zustand es muy minimalista y usa hooks.',
  ),
  92 => 
  array (
    'pregunta' => '¿Qué es SSR?',
    'opcion_a' => 'Server-Side Rendering',
    'opcion_b' => 'Static Site React',
    'opcion_c' => 'Single State Render',
    'opcion_d' => 'Sync State React',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Renderiza HTML en el servidor antes de enviar.',
  ),
  93 => 
  array (
    'pregunta' => '¿Qué es SSG?',
    'opcion_a' => 'Static Site Generation',
    'opcion_b' => 'Server Side GraphQL',
    'opcion_c' => 'Single Site Generator',
    'opcion_d' => 'Static State Git',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Genera HTML en tiempo de construcción (build).',
  ),
  94 => 
  array (
    'pregunta' => '¿Qué es CSR?',
    'opcion_a' => 'Client-Side Rendering',
    'opcion_b' => 'Cascading Style React',
    'opcion_c' => 'Component Style Rule',
    'opcion_d' => 'Client Server Route',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'React clásico donde el navegador dibuja todo.',
  ),
  95 => 
  array (
    'pregunta' => '¿Qué framework React es recomendado para sitios estáticos?',
    'opcion_a' => 'Gatsby',
    'opcion_b' => 'Next.js',
    'opcion_c' => 'CRA',
    'opcion_d' => 'Remix',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Gatsby se enfoca en SSG con GraphQL.',
  ),
  96 => 
  array (
    'pregunta' => '¿Qué tipo de componente usa la palabra clave class?',
    'opcion_a' => 'Class Component',
    'opcion_b' => 'Functional Component',
    'opcion_c' => 'Pure Component',
    'opcion_d' => 'HOC',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Son componentes legacy basados en clases.',
  ),
  97 => 
  array (
    'pregunta' => '¿Qué método de clase se llamaba al desmontar el componente?',
    'opcion_a' => 'componentWillUnmount',
    'opcion_b' => 'unmount',
    'opcion_c' => 'destroy',
    'opcion_d' => 'clean',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Ideal para limpiar temporizadores y eventos.',
  ),
  98 => 
  array (
    'pregunta' => '¿Qué comando detiene la ejecución de useEffect?',
    'opcion_a' => 'return () => {}',
    'opcion_b' => 'stop()',
    'opcion_c' => 'break',
    'opcion_d' => 'clear()',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Retornar una función sirve de cleanup.',
  ),
  99 => 
  array (
    'pregunta' => '¿Qué símbolo denota un fragmento vacío en JSX?',
    'opcion_a' => '<></>',
    'opcion_b' => '<!>',
    'opcion_c' => '<?>',
    'opcion_d' => '||',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Es la sintaxis corta para Fragments.',
  ),
);
}
