<?php
function get_cloud_ia_bank() {
    return array (
  0 => 
  array (
    'pregunta' => '¿Qué es la computación en la nube (Cloud Computing)?',
    'opcion_a' => 'La entrega de servicios de cómputo (servidores, storage, DB) por internet.',
    'opcion_b' => 'Un tipo de hardware instalado en oficinas para procesar datos localmente.',
    'opcion_c' => 'Un protocolo de comunicación para transferir datos entre dispositivos.',
    'opcion_d' => 'Una red privada que conecta múltiples centros de datos corporativos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Cloud Computing ofrece recursos bajo demanda (IaaS, PaaS, SaaS) con pago por uso.',
  ),
  1 => 
  array (
    'pregunta' => '¿Qué es Kubernetes en el contexto de aplicaciones IA en la nube?',
    'opcion_a' => 'Un orquestador de contenedores para desplegar y escalar aplicaciones.',
    'opcion_b' => 'Un framework de ML para entrenar modelos en múltiples GPUs en paralelo.',
    'opcion_c' => 'Una plataforma de monitoreo de modelos de IA en tiempo real.',
    'opcion_d' => 'Un sistema de bases de datos distribuidas para almacenar embeddings.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Kubernetes gestiona pods de contenedores, auto-scaling y load balancing para APIs de IA.',
  ),
  2 => 
  array (
    'pregunta' => '¿Qué es el alucinamiento (hallucination) en LLMs?',
    'opcion_a' => 'Cuando el modelo genera información falsa o inventada como si fuera verdadera.',
    'opcion_b' => 'Cuando el modelo genera respuestas repetidas sin variación creativa.',
    'opcion_c' => 'Cuando el modelo rechaza responder por restricciones de seguridad.',
    'opcion_d' => 'Cuando el modelo olvida el contexto previo de la conversación actual.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Las alucinaciones ocurren porque los LLMs predicen tokens plausibles, no verifican hechos.',
  ),
  3 => 
  array (
    'pregunta' => '¿Qué hace la técnica Few-Shot Prompting?',
    'opcion_a' => 'Incluye algunos ejemplos de entradas y salidas en el prompt para guiar al modelo.',
    'opcion_b' => 'Entrena el modelo con pocos ejemplos de forma rápida y eficiente.',
    'opcion_c' => 'Reduce la cantidad de tokens del prompt para ahorrar costos de API.',
    'opcion_d' => 'Selecciona pocos tokens relevantes del contexto para responder.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Few-shot: prompt="Traducir inglés→español. apple→manzana. car→coche. house→?"',
  ),
  4 => 
  array (
    'pregunta' => '¿Qué es MLflow en el contexto de MLOps?',
    'opcion_a' => 'Una plataforma open-source para rastrear experimentos y versionar modelos ML.',
    'opcion_b' => 'Un framework de ML de Google para entrenar redes neuronales en la nube.',
    'opcion_c' => 'Un orquestador de pipelines de datos para preparar datasets de entrenamiento.',
    'opcion_d' => 'Una herramienta de visualización de métricas de modelos en producción.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'MLflow registra parámetros, métricas y artefactos por experimento para reproducibilidad.',
  ),
  5 => 
  array (
    'pregunta' => '¿Qué es el Chain-of-Thought (CoT) prompting?',
    'opcion_a' => 'Técnica que pide al modelo razonar paso a paso antes de dar la respuesta.',
    'opcion_b' => 'Encadenar múltiples LLMs donde la salida de uno es la entrada del siguiente.',
    'opcion_c' => 'Una cadena de prompts almacenados en base de datos para reutilización.',
    'opcion_d' => 'Técnica para reducir tokens concatenando prompts relacionados entre sí.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '"Piensa paso a paso" mejora la precisión en tareas de razonamiento matemático y lógico.',
  ),
  6 => 
  array (
    'pregunta' => '¿Qué es el Model Context Protocol (MCP) de Anthropic?',
    'opcion_a' => 'Un protocolo estándar para conectar LLMs con herramientas y fuentes de datos.',
    'opcion_b' => 'Un protocolo para gestionar el contexto de múltiples sesiones del mismo LLM.',
    'opcion_c' => 'Un sistema de caché para reutilizar el KV cache entre diferentes llamadas.',
    'opcion_d' => 'Un protocolo de seguridad para validar los prompts antes de procesarlos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'MCP estandariza cómo los LLMs acceden a tools, recursos y prompts de sistemas externos.',
  ),
  7 => 
  array (
    'pregunta' => '¿Qué es el RLHF (Reinforcement Learning from Human Feedback)?',
    'opcion_a' => 'Técnica para alinear LLMs usando evaluaciones humanas como señal de recompensa.',
    'opcion_b' => 'Un método para entrenar robots físicos usando retroalimentación de humanos.',
    'opcion_c' => 'Un proceso de validación donde humanos revisan los datasets de entrenamiento.',
    'opcion_d' => 'Un sistema de aprendizaje activo donde el modelo pregunta al usuario.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'RLHF: supervisado → reward model con preferencias humanas → RL (PPO) para alinear el LLM.',
  ),
  8 => 
  array (
    'pregunta' => '¿Qué hace el prompt system message en APIs de LLMs como OpenAI?',
    'opcion_a' => 'Define el rol, restricciones y comportamiento base del asistente de IA.',
    'opcion_b' => 'Configura los parámetros técnicos como temperatura y max tokens de la API.',
    'opcion_c' => 'Inicializa el historial de conversación con mensajes previos del usuario.',
    'opcion_d' => 'Define las funciones (tools) que el modelo puede invocar durante la sesión.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'System message: "Eres un asistente experto en COBOL que responde en español conciso."',
  ),
  9 => 
  array (
    'pregunta' => '¿Qué es la perplexity y cómo se usa para evaluar LLMs?',
    'opcion_a' => 'El exponente de la entropía cruzada; menor valor indica mejor modelado del lenguaje.',
    'opcion_b' => 'El número de respuestas únicas que el modelo genera para el mismo prompt.',
    'opcion_c' => 'La varianza de las respuestas del modelo medida en múltiples ejecuciones.',
    'opcion_d' => 'El número de tokens de contexto que el modelo puede recordar correctamente.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Perplexity = e^(H); mide cuán sorprendido está el modelo ante el corpus de evaluación.',
  ),
  10 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 1?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  11 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 2?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  12 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 3?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  13 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 4?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  14 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 5?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  15 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 6?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  16 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 7?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  17 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 8?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  18 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 9?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  19 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 10?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  20 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 11?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  21 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 12?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  22 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 13?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  23 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 14?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  24 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 15?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  25 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 16?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  26 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 17?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  27 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 18?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  28 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 19?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  29 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 20?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  30 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 21?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  31 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 22?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  32 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 23?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  33 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 24?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  34 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 25?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  35 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 26?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  36 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 27?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  37 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 28?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  38 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 29?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  39 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 30?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  40 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 31?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  41 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 32?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  42 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 33?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  43 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 34?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  44 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 35?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  45 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 36?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  46 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 37?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  47 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 38?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  48 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 39?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  49 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 40?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  50 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 41?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  51 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 42?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  52 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 43?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  53 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 44?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  54 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 45?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  55 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 46?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  56 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 47?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  57 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 48?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  58 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 49?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  59 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 50?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  60 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 51?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  61 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 52?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  62 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 53?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  63 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 54?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  64 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 55?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  65 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 56?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  66 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 57?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  67 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 58?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  68 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 59?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  69 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 60?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  70 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 61?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  71 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 62?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  72 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 63?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  73 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 64?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  74 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 65?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  75 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 66?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  76 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 67?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  77 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 68?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  78 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 69?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  79 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 70?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  80 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 71?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  81 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 72?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  82 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 73?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  83 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 74?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  84 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 75?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  85 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 76?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  86 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 77?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  87 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 78?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  88 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 79?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  89 => 
  array (
    'pregunta' => '¿Qué modelo se usa en IA generativa 80?',
    'opcion_a' => 'LLM',
    'opcion_b' => 'CNN',
    'opcion_c' => 'RNN',
    'opcion_d' => 'SVM',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LLM es la base de IA generativa moderna.',
  ),
  90 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 81',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 81 generada.',
  ),
  91 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 82',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 82 generada.',
  ),
  92 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 83',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 83 generada.',
  ),
  93 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 84',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 84 generada.',
  ),
  94 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 85',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 85 generada.',
  ),
  95 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 86',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 86 generada.',
  ),
  96 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 87',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 87 generada.',
  ),
  97 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 88',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 88 generada.',
  ),
  98 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 89',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 89 generada.',
  ),
  99 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 90',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 90 generada.',
  ),
);
}
