<?php
function get_cobol_bank() {
    return array (
  0 => 
  array (
    'pregunta' => '¿Cuál es el orden correcto de las cuatro divisiones en un programa COBOL?',
    'opcion_a' => 'IDENTIFICATION, ENVIRONMENT, DATA, PROCEDURE DIVISION.',
    'opcion_b' => 'DATA, IDENTIFICATION, ENVIRONMENT, PROCEDURE DIVISION.',
    'opcion_c' => 'ENVIRONMENT, DATA, PROCEDURE, IDENTIFICATION DIVISION.',
    'opcion_d' => 'PROCEDURE, DATA, ENVIRONMENT, IDENTIFICATION DIVISION.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'El compilador COBOL exige ese orden fijo: IDENTIFICATION, ENVIRONMENT, DATA, PROCEDURE.',
  ),
  1 => 
  array (
    'pregunta' => '¿Qué sección de la DATA DIVISION se usa para declarar variables de trabajo?',
    'opcion_a' => 'WORKING-STORAGE SECTION.',
    'opcion_b' => 'FILE SECTION.',
    'opcion_c' => 'LINKAGE SECTION.',
    'opcion_d' => 'LOCAL-STORAGE SECTION.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'WORKING-STORAGE contiene variables que persisten durante toda la ejecución del programa.',
  ),
  2 => 
  array (
    'pregunta' => '¿Qué significa PIC 9(4) en COBOL?',
    'opcion_a' => 'Un campo numérico de 4 dígitos sin signo.',
    'opcion_b' => 'Un campo alfabético de 4 caracteres.',
    'opcion_c' => 'Un campo numérico con 4 decimales.',
    'opcion_d' => 'Una tabla de 4 elementos numéricos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'PIC 9(4) define un campo de 4 posiciones numéricas de 0-9 sin signo.',
  ),
  3 => 
  array (
    'pregunta' => '¿Qué nivel de dato se usa para definir registros de un archivo en la FILE SECTION?',
    'opcion_a' => 'Nivel 01.',
    'opcion_b' => 'Nivel 05.',
    'opcion_c' => 'Nivel 77.',
    'opcion_d' => 'Nivel 88.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Los registros de archivo se definen al nivel 01 dentro de la FILE SECTION.',
  ),
  4 => 
  array (
    'pregunta' => '¿Qué verbo COBOL se usa para leer el siguiente registro de un archivo secuencial?',
    'opcion_a' => 'READ nombre-archivo NEXT RECORD.',
    'opcion_b' => 'GET NEXT RECORD FROM archivo.',
    'opcion_c' => 'FETCH archivo INTO registro.',
    'opcion_d' => 'SELECT NEXT FROM nombre-archivo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'READ lee el siguiente registro; al llegar al fin de archivo activa la condición AT END.',
  ),
  5 => 
  array (
    'pregunta' => '¿Cuál es la función del verbo PERFORM en COBOL?',
    'opcion_a' => 'Ejecutar un párrafo o sección, con o sin repetición.',
    'opcion_b' => 'Abrir un archivo para lectura o escritura.',
    'opcion_c' => 'Definir un módulo externo y enlazarlo.',
    'opcion_d' => 'Calcular operaciones aritméticas básicas.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'PERFORM invoca párrafos o secciones y soporta UNTIL, TIMES y VARYING para bucles.',
  ),
  6 => 
  array (
    'pregunta' => '¿Qué hace la cláusula STOP RUN en COBOL?',
    'opcion_a' => 'Termina la ejecución del programa y devuelve el control al sistema operativo.',
    'opcion_b' => 'Pausa temporalmente el programa esperando input del usuario.',
    'opcion_c' => 'Cierra todos los archivos abiertos sin finalizar el programa.',
    'opcion_d' => 'Llama al módulo de recuperación de errores del sistema.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'STOP RUN finaliza el programa devolviendo el control al sistema operativo (o llamador).',
  ),
  7 => 
  array (
    'pregunta' => '¿Qué hace el verbo COMPUTE en COBOL?',
    'opcion_a' => 'Evalúa una expresión aritmética y almacena el resultado en una variable.',
    'opcion_b' => 'Compara dos variables y decide qué rama de código ejecutar.',
    'opcion_c' => 'Calcula la longitud en bytes de una cadena de caracteres.',
    'opcion_d' => 'Invoca un módulo externo para cálculos científicos complejos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'COMPUTE permite usar expresiones como COMPUTE WS-RESULTADO = WS-A + WS-B * 2.',
  ),
  8 => 
  array (
    'pregunta' => '¿Qué cláusula en SELECT asocia un nombre lógico de archivo con el físico?',
    'opcion_a' => 'ASSIGN TO nombre-externo.',
    'opcion_b' => 'LINK TO nombre-archivo.',
    'opcion_c' => 'MAP TO ruta-sistema.',
    'opcion_d' => 'BIND TO nombre-dataset.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'SELECT ... ASSIGN TO enlaza el nombre interno COBOL con el nombre de DD en JCL.',
  ),
  9 => 
  array (
    'pregunta' => '¿Qué indica PIC X(20) en COBOL?',
    'opcion_a' => 'Un campo alfanumérico de 20 caracteres.',
    'opcion_b' => 'Un campo numérico de 20 dígitos.',
    'opcion_c' => 'Una tabla de 20 campos numéricos.',
    'opcion_d' => 'Un campo con valor hexadecimal de 20 bytes.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'X en PIC indica alfanumérico; X(20) reserva 20 bytes de almacenamiento.',
  ),
  10 => 
  array (
    'pregunta' => '¿Qué verbo COBOL se usa para llamar a un subprograma externo?',
    'opcion_a' => 'CALL nombre-modulo.',
    'opcion_b' => 'INVOKE nombre-modulo.',
    'opcion_c' => 'EXECUTE nombre-modulo.',
    'opcion_d' => 'RUN nombre-modulo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CALL invoca un subprograma pasando parámetros mediante la cláusula USING.',
  ),
  11 => 
  array (
    'pregunta' => '¿Cuándo se activa la cláusula AT END en un verbo READ?',
    'opcion_a' => 'Cuando se ha leído el último registro y no hay más datos.',
    'opcion_b' => 'Cuando hay un error de E/S al intentar leer el archivo.',
    'opcion_c' => 'Cuando el registro leído tiene todos los campos en cero.',
    'opcion_d' => 'Cuando el archivo supera el tamaño máximo permitido.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'AT END (EOF) se dispara cuando READ no encuentra más registros; permite el fin de ciclo.',
  ),
  12 => 
  array (
    'pregunta' => '¿Qué hace la cláusula CORRESPONDING (CORR) en COBOL?',
    'opcion_a' => 'Mueve o suma campos con el mismo nombre entre dos grupos.',
    'opcion_b' => 'Copia la estructura completa de un copybook al programa.',
    'opcion_c' => 'Compara dos registros campo a campo y retorna diferencias.',
    'opcion_d' => 'Define correspondencias entre variables y campos de DB2.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'MOVE CORRESPONDING mueve los campos de mismo nombre de origen a destino automáticamente.',
  ),
  13 => 
  array (
    'pregunta' => '¿Qué función tiene FILE STATUS en COBOL?',
    'opcion_a' => 'Almacena un código de dos caracteres con el resultado de la última operación de IO.',
    'opcion_b' => 'Muestra el nombre del archivo actualmente abierto en el panel de control.',
    'opcion_c' => 'Define el tamaño máximo del archivo en bytes antes de la apertura.',
    'opcion_d' => 'Indica el número de registros escritos desde la última apertura del archivo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'FILE STATUS retorna "00" (éxito), "10" (EOF), "23" (no encontrado) tras cada operación IO.',
  ),
  14 => 
  array (
    'pregunta' => '¿Para qué sirve la sentencia //DD en JCL?',
    'opcion_a' => 'Asociar el nombre lógico del archivo COBOL (DDNAME) con el dataset físico.',
    'opcion_b' => 'Definir las variables de entorno para el paso de ejecución.',
    'opcion_c' => 'Declarar el número de procesadores asignados al trabajo.',
    'opcion_d' => 'Especificar las prioridades de impresión del paso batch.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => '//DD enlaza el SELECT...ASSIGN del programa con el dataset real mediante el parámetro DSN.',
  ),
  15 => 
  array (
    'pregunta' => '¿Qué hace DISP=(NEW,CATLG,DELETE) en un DD de JCL?',
    'opcion_a' => 'Crea el dataset, lo cataloga si el job termina bien, o lo borra si falla.',
    'opcion_b' => 'Lee un dataset nuevo, lo cataloga siempre y lo borra al final.',
    'opcion_c' => 'Abre el dataset existente, no lo cataloga y lo retiene sin importar el resultado.',
    'opcion_d' => 'Crea el dataset temporal, lo pasa al siguiente paso y lo elimina al terminar.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Los tres subparámetros son: estado-inicial, disposición-normal y disposición-anormal.',
  ),
  16 => 
  array (
    'pregunta' => '¿Qué es un dataset temporal en JCL y cómo se identifica?',
    'opcion_a' => 'Un dataset con nombre que empieza por && que se borra al terminar el job.',
    'opcion_b' => 'Un dataset con nombre que empieza por ## usado como trabajo permanente.',
    'opcion_c' => 'Un dataset sin DSN que persiste en disco aunque el job falle.',
    'opcion_d' => 'Un dataset catalogado con atributo TEMP que caduca en 7 días.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Los datasets temporales (&&nombre) son automáticamente eliminados al terminar el job.',
  ),
  17 => 
  array (
    'pregunta' => '¿Cuál es la función del programa IEFBR14 en JCL?',
    'opcion_a' => 'No hace nada; se usa para crear o borrar datasets mediante las DDs del paso.',
    'opcion_b' => 'Ordena los registros de un dataset según campos definidos en tarjetas SYSIN.',
    'opcion_c' => 'Copia un dataset completo de origen a destino sin modificación.',
    'opcion_d' => 'Genera un listado de todos los datasets catalogados en el volumen.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'IEFBR14 solo retorna RC=0; su utilidad es que JCL procesa los DDs: crea/borra datasets.',
  ),
  18 => 
  array (
    'pregunta' => '¿Qué hace el programa IEBGENER en JCL?',
    'opcion_a' => 'Copia un dataset secuencial de SYSUT1 a SYSUT2 registro por registro.',
    'opcion_b' => 'Genera claves primarias para registros de datasets VSAM KSDS.',
    'opcion_c' => 'Crea catálogos del sistema en el volumen de disco especificado.',
    'opcion_d' => 'Imprime el contenido hexadecimal de cualquier tipo de dataset.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'IEBGENER copia archivos secuenciales; SYSUT1=entrada, SYSUT2=salida, SYSIN=DD DUMMY.',
  ),
  19 => 
  array (
    'pregunta' => '¿Qué hace la cláusula REDEFINES en la DATA DIVISION de COBOL?',
    'opcion_a' => 'Permite que diferentes descripciones compartan el mismo espacio de memoria.',
    'opcion_b' => 'Cambia el nombre de un campo en el diccionario de datos del sistema.',
    'opcion_c' => 'Convierte automáticamente un campo numérico en texto Unicode.',
    'opcion_d' => 'Elimina un campo de la memoria liberando su espacio de almacenamiento.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'REDEFINES superpone dos estructuras en el mismo bloque de memoria sin duplicar espacio.',
  ),
  20 => 
  array (
    'pregunta' => '¿Cuál es la diferencia entre SEARCH y SEARCH ALL en tablas COBOL?',
    'opcion_a' => 'SEARCH es lineal O(n); SEARCH ALL es binario O(log n) y requiere tabla ordenada.',
    'opcion_b' => 'SEARCH busca texto; SEARCH ALL busca exclusivamente valores numéricos.',
    'opcion_c' => 'SEARCH ALL modifica la tabla eliminando duplicados durante la búsqueda.',
    'opcion_d' => 'No hay diferencia funcional; es solo preferencia de estilo de código.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'SEARCH ALL requiere ASCENDING/DESCENDING KEY definida en OCCURS y tabla ya ordenada.',
  ),
  21 => 
  array (
    'pregunta' => '¿Qué indica OCCURS 10 TIMES INDEXED BY WS-IDX en COBOL?',
    'opcion_a' => 'Define una tabla de 10 elementos accesibles mediante el índice WS-IDX.',
    'opcion_b' => 'Repite la sección del programa exactamente 10 veces de forma automática.',
    'opcion_c' => 'Crea 10 archivos separados con el mismo layout de registro.',
    'opcion_d' => 'Indica que el campo puede aparecer entre 1 y 10 veces en el registro.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'OCCURS con INDEXED BY usa un valor de índice interno (no subíndice) para acceso eficiente.',
  ),
  22 => 
  array (
    'pregunta' => '¿Cuándo se usa OCCURS DEPENDING ON en COBOL?',
    'opcion_a' => 'Para definir tablas de longitud variable cuyo tamaño se determina en tiempo de ejecución.',
    'opcion_b' => 'Para definir tablas que dependen de la versión del compilador instalado.',
    'opcion_c' => 'Para indicar que la tabla solo existe si una condición es verdadera.',
    'opcion_d' => 'Para tablas cuyos elementos se cargan desde un archivo VSAM externo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'ODO permite tablas de hasta OCCURS MAX TIMES donde el recuento real está en otro campo.',
  ),
  23 => 
  array (
    'pregunta' => '¿Qué significa un FILE-STATUS "23" en COBOL?',
    'opcion_a' => 'No se encontró el registro solicitado (KEY NOT FOUND) en un archivo indexado.',
    'opcion_b' => 'El archivo tiene 23 registros menos de los esperados por el programa.',
    'opcion_c' => 'Se produjo un error de E/S irrecuperable en el dispositivo de almacenamiento.',
    'opcion_d' => 'El archivo fue abierto por otro programa con modo exclusivo (OLD).',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '"23" es "Record Not Found" en archivos con acceso directo (VSAM KSDS, RRDS).',
  ),
  24 => 
  array (
    'pregunta' => '¿Qué hace EVALUATE TRUE en COBOL?',
    'opcion_a' => 'Evalúa una serie de condiciones y ejecuta el caso cuya condición sea verdadera.',
    'opcion_b' => 'Verifica que todas las variables de la sección sean inicialmente verdaderas.',
    'opcion_c' => 'Fuerza al compilador a optimizar el código eliminando ramas muertas.',
    'opcion_d' => 'Comprueba la integridad de los datos antes de procesarlos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'EVALUATE TRUE ... WHEN condición es el equivalente moderno de IF/ELSE-IF encadenados.',
  ),
  25 => 
  array (
    'pregunta' => '¿Cuál es la función de INITIALIZE en COBOL?',
    'opcion_a' => 'Pone a cero los numéricos y espacios los alfanuméricos de un grupo o variable.',
    'opcion_b' => 'Abre todos los archivos declarados en la FILE SECTION simultáneamente.',
    'opcion_c' => 'Crea e inicializa las tablas internas con valores predeterminados del sistema.',
    'opcion_d' => 'Reinicia el contador de registros procesados al inicio de cada ciclo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'INITIALIZE equivale a MOVE ZEROS/SPACES al grupo completo, incluyendo subelementos.',
  ),
  26 => 
  array (
    'pregunta' => '¿Qué hace STRING en COBOL?',
    'opcion_a' => 'Concatena varias cadenas o campos en una sola variable destino.',
    'opcion_b' => 'Convierte una cadena de texto en una estructura de campos numéricos.',
    'opcion_c' => 'Compara dos cadenas y retorna la más corta como resultado.',
    'opcion_d' => 'Define un campo de longitud variable terminado en un delimitador especial.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'STRING permite unir múltiples campos con delimitadores opcionales en una sola variable.',
  ),
  27 => 
  array (
    'pregunta' => '¿Qué hace el verbo INSPECT en COBOL?',
    'opcion_a' => 'Cuenta o reemplaza ocurrencias de caracteres o cadenas en una variable.',
    'opcion_b' => 'Valida la estructura de un registro contra el layout definido en FILE SECTION.',
    'opcion_c' => 'Imprime en SYSOUT el contenido actual de todas las variables del grupo.',
    'opcion_d' => 'Genera un informe de auditoría de todas las lecturas del archivo de entrada.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'INSPECT ... TALLYING cuenta ocurrencias; INSPECT ... REPLACING sustituye caracteres.',
  ),
  28 => 
  array (
    'pregunta' => '¿Qué ventaja tiene COMP-3 (PACKED-DECIMAL) sobre DISPLAY en COBOL?',
    'opcion_a' => 'Guarda 2 dígitos por byte ahorrando espacio y permite operaciones rápidas.',
    'opcion_b' => 'Permite almacenar hasta el doble de dígitos en el mismo espacio.',
    'opcion_c' => 'Elimina la necesidad del signo en cálculos matemáticos positivos.',
    'opcion_d' => 'Solo funciona con DB2 y no puede usarse en archivos secuenciales.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'COMP-3 (PACKED) almacena 2 dígitos por byte más un nibble de signo, optimizando espacio.',
  ),
  29 => 
  array (
    'pregunta' => '¿Cuándo se usa la sentencia EXEC SQL en COBOL?',
    'opcion_a' => 'Para embeber sentencias SQL de DB2 directamente en el programa COBOL.',
    'opcion_b' => 'Para ejecutar scripts de administración de base de datos del mainframe.',
    'opcion_c' => 'Para llamar módulos de acceso a VSAM mediante la interfaz SQL.',
    'opcion_d' => 'Para declarar variables de host que usará el precompilador DB2.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'EXEC SQL ... END-EXEC embebe SQL; el precompilador DB2 lo transforma en llamadas CALL.',
  ),
  30 => 
  array (
    'pregunta' => '¿Qué es el SQLCA y qué campo se revisa tras cada EXEC SQL?',
    'opcion_a' => 'SQL Communication Area; se revisa SQLCODE (0=OK, +100=no encontrado, negativo=error).',
    'opcion_b' => 'SQL Control Area; se revisa SQLSTATE para ver el mensaje de texto del error.',
    'opcion_c' => 'SQL Count Area; se revisa SQLN para conocer las filas afectadas.',
    'opcion_d' => 'SQL Cache Area; se revisa SQLRCODE para validar el plan de acceso.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'SQLCA (include SQLCA) provee SQLCODE; 0=éxito, +100=EOF, negativo=error DB2.',
  ),
  31 => 
  array (
    'pregunta' => '¿Qué hace el verbo EXEC CICS SEND MAP en un programa COBOL CICS?',
    'opcion_a' => 'Envía un mapa (pantalla BMS) al terminal del usuario para mostrar datos.',
    'opcion_b' => 'Transfiere datos a la cola CICS para procesamiento asíncrono.',
    'opcion_c' => 'Envía el registro procesado al archivo VSAM indicado en el MAP.',
    'opcion_d' => 'Manda un mensaje de error al log del sistema CICS JES.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'SEND MAP presenta la pantalla BMS con los datos del MAPSET al terminal 3270.',
  ),
  32 => 
  array (
    'pregunta' => '¿Qué sentencias JCL reemplazan la compleja lógica COND para flujo condicional?',
    'opcion_a' => 'Las sentencias // IF / THEN / ELSE / ENDIF basadas en RC o ABEND.',
    'opcion_b' => 'Las sentencias //WHEN y //OTHERWISE del sistema JES3.',
    'opcion_c' => 'Los bloques //CASE y //ESAC disponibles en versiones z/OS recientes.',
    'opcion_d' => 'Las directivas //CHECK y //SKIP del compilador de procedimientos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '// IF (STEP1.RC = 0) THEN ... // ENDIF es más legible que la antigua sintaxis COND.',
  ),
  33 => 
  array (
    'pregunta' => '¿Qué significa COND=EVEN en una sentencia //EXEC de JCL?',
    'opcion_a' => 'El paso se ejecuta aunque pasos anteriores hayan terminado con ABEND.',
    'opcion_b' => 'El paso se ejecuta solo cuando el código de retorno previo es par.',
    'opcion_c' => 'El paso se ejecuta únicamente en LPAR con número de CPU par.',
    'opcion_d' => 'El paso se ejecuta si el job anterior en la cadena finalizó correctamente.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'COND=EVEN ejecuta el paso incluso si hubo ABEND previo; útil para limpieza de recursos.',
  ),
  34 => 
  array (
    'pregunta' => '¿Qué hace el programa IDCAMS en JCL?',
    'opcion_a' => 'Administra datasets VSAM: crea, borra, lista, copia y repara catálogos.',
    'opcion_b' => 'Ordena registros de datasets secuenciales en orden ascendente o descendente.',
    'opcion_c' => 'Copia módulos de carga entre bibliotecas PDS del sistema.',
    'opcion_d' => 'Genera reportes de espacio disponible en los volúmenes DASD del sistema.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'IDCAMS es el Access Method Services; procesa comandos como DEFINE CLUSTER, DELETE, REPRO.',
  ),
  35 => 
  array (
    'pregunta' => '¿Para qué se usa DFSORT en JCL y cuál es su DD principal de control?',
    'opcion_a' => 'Ordena o mezcla datasets; las tarjetas de control van en el DD SORTIN/SYSIN.',
    'opcion_b' => 'Genera datasets de diagnóstico; las opciones se pasan en el DD SORTOUT.',
    'opcion_c' => 'Copia datasets con transformación; las reglas van en el DD SYSUT1.',
    'opcion_d' => 'Filtra registros de DB2; las condiciones van en el DD SORTWORK.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'DFSORT usa SORTIN (entrada), SORTOUT (salida) y SYSIN (tarjetas SORT FIELDS= o INCLUDE=).',
  ),
  36 => 
  array (
    'pregunta' => '¿Qué hace el parámetro RESTART en una sentencia //JOB de JCL?',
    'opcion_a' => 'Reinicia el job desde un paso específico sin reejecutar los pasos anteriores.',
    'opcion_b' => 'Reinicia automáticamente el job desde el inicio en caso de error o ABEND.',
    'opcion_c' => 'Activa el módulo de checkpoint para guardar el estado cada N registros.',
    'opcion_d' => 'Transfiere el job a una clase diferente de ejecución al reiniciar.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'RESTART=nombre-paso permite reanudar desde ese paso sin repetir los completados.',
  ),
  37 => 
  array (
    'pregunta' => '¿Qué hace el parámetro REGION en una sentencia //JOB o //EXEC de JCL?',
    'opcion_a' => 'Define la cantidad máxima de memoria virtual asignada al job o paso.',
    'opcion_b' => 'Indica la región geográfica del centro de datos donde se ejecuta el job.',
    'opcion_c' => 'Especifica el número de región de CICS a la que se conecta el programa.',
    'opcion_d' => 'Define el área de memoria compartida entre los pasos del mismo job.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'REGION=128M asigna hasta 128MB al job/paso; si se excede ocurre S80A o S878 ABEND.',
  ),
  38 => 
  array (
    'pregunta' => '¿Qué parámetro TIME en JCL limita el tiempo de CPU de un paso?',
    'opcion_a' => 'TIME=(minutos,segundos) establece el límite de CPU antes de generar S322.',
    'opcion_b' => 'TIME=NOLIMIT indica que el paso puede ejecutarse sin restricción de tiempo.',
    'opcion_c' => 'TIME=(horas,minutos) define la hora del día en que el paso debe iniciar.',
    'opcion_d' => 'TIME=MAX asigna el máximo de tiempo de CPU disponible en la clase.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Si el paso supera el TIME definido, z/OS genera ABEND S322 (tiempo de CPU excedido).',
  ),
  39 => 
  array (
    'pregunta' => '¿Qué es un ABEND S0C7 en un programa COBOL corriendo en z/OS?',
    'opcion_a' => 'Data Exception: operación aritmética con datos no numéricos en campo numérico.',
    'opcion_b' => 'Storage Violation: el programa accedió a memoria fuera de su región asignada.',
    'opcion_c' => 'Time Exceeded: el programa superó el tiempo de CPU máximo del paso.',
    'opcion_d' => 'Open Error: el programa intentó leer un archivo que no existe en el catálogo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'S0C7 ocurre cuando se opera aritmética sobre un campo DISPLAY con espacios o caracteres.',
  ),
  40 => 
  array (
    'pregunta' => '¿Cuál es la diferencia entre un PDS y un PDSE en z/OS?',
    'opcion_a' => 'PDSE permite miembros de tamaño variable y no requiere compactación periódica.',
    'opcion_b' => 'PDSE solo almacena módulos de carga mientras PDS almacena cualquier tipo.',
    'opcion_c' => 'PDS admite más de 200 miembros activos mientras PDSE está limitado a 10.',
    'opcion_d' => 'No hay diferencia funcional; PDSE es solo el nombre moderno de PDS.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'PDSE elimina la necesidad de IEBCOPY/compress; gestiona espacio libre automáticamente.',
  ),
  41 => 
  array (
    'pregunta' => '¿Cómo se declara un cursor DB2 en COBOL y cuándo se usa OPEN CURSOR?',
    'opcion_a' => 'Con EXEC SQL DECLARE cursor CURSOR FOR SELECT; se abre con EXEC SQL OPEN cursor.',
    'opcion_b' => 'Con EXEC SQL CREATE CURSOR en WORKING-STORAGE; se abre con EXEC CICS OPEN.',
    'opcion_c' => 'Con un SELECT simple en EXEC SQL; el cursor se abre automáticamente.',
    'opcion_d' => 'Con EXEC SQL DEFINE CURSOR al inicio de PROCEDURE DIVISION.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'DECLARE define el cursor; OPEN lo materializa; FETCH recupera fila por fila; CLOSE libera.',
  ),
  42 => 
  array (
    'pregunta' => '¿Qué es un deadlock en DB2 y cómo se maneja en COBOL?',
    'opcion_a' => 'Bloqueo circular entre transacciones; DB2 aborta una y retorna SQLCODE -911.',
    'opcion_b' => 'Un timeout de red que DB2 detecta y retorna SQLCODE -922 al programa.',
    'opcion_c' => 'Un error de sintaxis SQL que el precompilador detecta en tiempo de compilación.',
    'opcion_d' => 'Una condición de espera en CICS cuando dos transacciones leen el mismo mapa.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'SQLCODE -911 (deadlock) o -913 (timeout) requieren ROLLBACK y reintentar la transacción.',
  ),
  43 => 
  array (
    'pregunta' => '¿Qué hace EXEC CICS SYNCPOINT en un programa CICS COBOL?',
    'opcion_a' => 'Confirma (commit) todos los cambios de la unidad de trabajo actual en CICS.',
    'opcion_b' => 'Sincroniza los relojes de sistema entre el LPAR principal y el de backup.',
    'opcion_c' => 'Hace una pausa y espera a que otra transacción CICS libere un recurso.',
    'opcion_d' => 'Guarda el estado de la pantalla 3270 en una cola temporal para recuperación.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'SYNCPOINT es el COMMIT de CICS; SYNCPOINT ROLLBACK deshace los cambios de la UOW.',
  ),
  44 => 
  array (
    'pregunta' => '¿Qué es el COMMAREA en CICS y cómo se pasa entre transacciones?',
    'opcion_a' => 'Un área de datos compartida que se pasa con EXEC CICS RETURN TRANSID COMMAREA.',
    'opcion_b' => 'Una cola de mensajes de sistema que CICS mantiene entre todas las transacciones.',
    'opcion_c' => 'Una tabla de control que almacena los mapas BMS del sistema de pantallas.',
    'opcion_d' => 'Un archivo VSAM temporal que contiene el estado de la sesión del usuario.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'COMMAREA (hasta 32KB) se pasa entre pseudo-conversaciones via EXEC CICS RETURN COMMAREA.',
  ),
  45 => 
  array (
    'pregunta' => '¿Qué técnica permite a COBOL procesar registros con ABEND S0C7 y continuar?',
    'opcion_a' => 'Implementar una rutina ON EXCEPTION o verificar FILE-STATUS y SQLCODE.',
    'opcion_b' => 'Usar USAGE COMP-1 en todos los campos para prevenir errores de datos.',
    'opcion_c' => 'Agregar EXCEPTION HANDLING con TRY/CATCH como en Java o C#.',
    'opcion_d' => 'Declarar todos los campos numéricos como PIC X para evitar data exceptions.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'COBOL no tiene excepciones; se validan datos con IF NUMERIC antes de operar y FILE-STATUS.',
  ),
  46 => 
  array (
    'pregunta' => '¿Qué es el programa DSNUPROC en el contexto de DB2 batch COBOL?',
    'opcion_a' => 'El procedimiento de utilidades DB2 para RUNSTATS, REORG, LOAD y CHECK.',
    'opcion_b' => 'El módulo principal que compila y precompila programas COBOL con DB2.',
    'opcion_c' => 'Un procedimiento CICS que gestiona la conexión entre CICS y DB2.',
    'opcion_d' => 'La rutina de instalación del catálogo DB2 en el volumen de sistema.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'DSNUPROC ejecuta utilidades como RUNSTATS (estadísticas), REORG (reorganización) y LOAD.',
  ),
  47 => 
  array (
    'pregunta' => '¿Qué diferencia hay entre REWRITE y WRITE en un archivo VSAM COBOL?',
    'opcion_a' => 'REWRITE actualiza un registro existente ya leído; WRITE inserta un registro nuevo.',
    'opcion_b' => 'WRITE es más eficiente que REWRITE para grandes volúmenes de datos VSAM.',
    'opcion_c' => 'REWRITE puede insertar o actualizar; WRITE solo inserta en KSDS.',
    'opcion_d' => 'No hay diferencia; ambos verbos modifican registros del archivo VSAM.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'REWRITE actualiza el registro previamente leído con READ UPDATE; WRITE agrega uno nuevo.',
  ),
  48 => 
  array (
    'pregunta' => '¿Qué hace la cláusula WITH HOLD en un cursor DB2 de COBOL?',
    'opcion_a' => 'Mantiene el cursor abierto tras un COMMIT sin necesidad de reabrirlo.',
    'opcion_b' => 'Bloquea la tabla completa durante toda la vida del cursor.',
    'opcion_c' => 'Impide que otros programas accedan al mismo plan de acceso DB2.',
    'opcion_d' => 'Retiene los locks de fila hasta el final de la transacción CICS.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'WITH HOLD preserva el cursor tras COMMIT; sin él el cursor se cierra automáticamente.',
  ),
  49 => 
  array (
    'pregunta' => '¿Qué hace el verbo EXEC CICS LINK en COBOL CICS?',
    'opcion_a' => 'Llama a otro programa CICS pasando control y COMMAREA, retornando al llamador.',
    'opcion_b' => 'Enlaza un módulo externo a la memoria del task actual de CICS.',
    'opcion_c' => 'Crea un link de datos entre dos colas temporales de CICS.',
    'opcion_d' => 'Inicia una nueva transacción CICS de forma asíncrona sin esperar respuesta.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'EXEC CICS LINK invoca un subprograma y retorna; XCTL transfiere sin retorno al llamador.',
  ),
  50 => 
  array (
    'pregunta' => '¿Qué diferencia hay entre EXEC CICS LINK y EXEC CICS XCTL?',
    'opcion_a' => 'LINK retorna al programa llamador; XCTL transfiere el control sin retorno.',
    'opcion_b' => 'LINK es para módulos ASSEMBLER; XCTL es exclusivo para programas COBOL.',
    'opcion_c' => 'XCTL permite pasar COMMAREA mayor de 32KB; LINK está limitado a 32KB.',
    'opcion_d' => 'No hay diferencia práctica; ambos terminan la tarea CICS actual.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'LINK es como CALL (retorna); XCTL es como GO TO a otro programa (no retorna al llamador).',
  ),
  51 => 
  array (
    'pregunta' => '¿Cómo se implementa manejo de errores robusto en programas COBOL DB2 batch?',
    'opcion_a' => 'Verificar SQLCODE tras cada EXEC SQL; usar WHENEVER SQLERROR GO TO rutina.',
    'opcion_b' => 'Envolver cada EXEC SQL en un bloque TRY/CATCH de la extensión OO-COBOL.',
    'opcion_c' => 'Usar FILE-STATUS para capturar errores SQL igual que en archivos VSAM.',
    'opcion_d' => 'Activar el parámetro SQLCHECK=ALL en el JCL de compilación de DB2.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'WHENEVER SQLERROR GO TO rutina-error centraliza el manejo; luego revisa SQLCODE/SQLERRM.',
  ),
  52 => 
  array (
    'pregunta' => '¿Qué hace EXEC CICS WRITEQ TS en COBOL?',
    'opcion_a' => 'Escribe un item en una cola temporal (Temporary Storage) de CICS.',
    'opcion_b' => 'Escribe un registro en el archivo VSAM de la transacción actual.',
    'opcion_c' => 'Envía un mensaje de texto al terminal del usuario mediante la cola JES.',
    'opcion_d' => 'Registra una entrada en el log de auditoría del sistema CICS.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Temporary Storage Queue (TSQ) es como memoria compartida entre tasks CICS; TS es efímera.',
  ),
  53 => 
  array (
    'pregunta' => '¿Qué hace el comando IDCAMS REPRO en JCL?',
    'opcion_a' => 'Copia registros de un dataset (VSAM o secuencial) a otro dataset destino.',
    'opcion_b' => 'Repara la estructura de índices de un VSAM KSDS dañado.',
    'opcion_c' => 'Genera un reporte de diagnóstico del estado del catálogo VSAM.',
    'opcion_d' => 'Reproduce la ejecución de un job anterior usando los mismos parámetros.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'REPRO copia datos; puede cargar datos secuenciales en VSAM o copiar entre VSAM clusters.',
  ),
  54 => 
  array (
    'pregunta' => '¿Qué diferencia tiene EXEC SQL FETCH con FOR n ROWS en DB2 COBOL?',
    'opcion_a' => 'Permite recuperar múltiples filas en un solo FETCH usando un array host variable.',
    'opcion_b' => 'Limita el número máximo de filas que el cursor puede devolver en total.',
    'opcion_c' => 'Saltea n filas antes de retornar la primera fila del cursor.',
    'opcion_d' => 'Actualiza n filas del resultado del cursor en una sola operación.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'FETCH n ROWS (multi-row fetch) reduce las llamadas a DB2 y mejora performance en batch.',
  ),
  55 => 
  array (
    'pregunta' => '¿Qué es el COBOL precompiler y qué genera como salida?',
    'opcion_a' => 'Traduce EXEC SQL a llamadas CALL DSN... en COBOL puro para el compilador.',
    'opcion_b' => 'Genera código binario ejecutable directamente sin pasar por el compilador.',
    'opcion_c' => 'Produce un listado de los errores de SQL sin modificar el fuente COBOL.',
    'opcion_d' => 'Traduce COBOL a ASSEMBLER para optimización previa a la compilación.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'El precompilador DB2 sustituye EXEC SQL por CALL DSNHLI y genera el DBRM para el BIND.',
  ),
  56 => 
  array (
    'pregunta' => '¿Qué hace el comando IDCAMS DEFINE CLUSTER en JCL?',
    'opcion_a' => 'Crea un dataset VSAM especificando tipo (KSDS/ESDS/RRDS), espacio y clave.',
    'opcion_b' => 'Define un grupo de jobs relacionados que comparten el mismo espacio DASD.',
    'opcion_c' => 'Crea una biblioteca PDS con directorio de N bloques para miembros.',
    'opcion_d' => 'Establece un clúster de procesadores para paralelizar el job batch.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'DEFINE CLUSTER(NAME(...) INDEXED KEYS(...) CYL(...)) crea el VSAM con sus componentes.',
  ),
  57 => 
  array (
    'pregunta' => '¿Cómo se sobrescribe un DD de un PROC catalogado desde el JCL del job?',
    'opcion_a' => 'Codificando //nombre-paso.nombre-DD DD DSN=... después del //EXEC PROC.',
    'opcion_b' => 'Editando directamente el miembro del PROC en SYS1.PROCLIB antes del job.',
    'opcion_c' => 'Usando el parámetro OVERRIDE=DD en la sentencia //EXEC PROC.',
    'opcion_d' => 'Agregando un DD con DISP=OLD después del // END del PROC en el stream.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => '//PASO.DDNAME DD DSN=nuevo-dataset sobrescribe el DD definido dentro del PROC catalogado.',
  ),
  58 => 
  array (
    'pregunta' => '¿Qué hace el programa DFSORT con la tarjeta de control INCLUDE COND?',
    'opcion_a' => 'Solo incluye en la salida los registros que cumplen la condición especificada.',
    'opcion_b' => 'Incluye el dataset de control adicional en la entrada del sort.',
    'opcion_c' => 'Agrega los registros del dataset SORTIN2 basándose en una condición de campo.',
    'opcion_d' => 'Fuerza la inclusión de registros duplicados que normalmente serían omitidos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'INCLUDE COND=(pos,len,tipo,op,valor) filtra registros antes del ordenamiento o copia.',
  ),
  59 => 
  array (
    'pregunta' => '¿Qué es la clase de trabajo (CLASS) en JCL y cómo afecta la ejecución?',
    'opcion_a' => 'Define en qué iniciadores (initiators) puede correr el job según prioridad y recursos.',
    'opcion_b' => 'Determina la clase de seguridad RACF que controla el acceso a los datasets.',
    'opcion_c' => 'Indica la clase de error (ABEND) que el job reportará al operador del sistema.',
    'opcion_d' => 'Define la clase de almacenamiento DASD donde se crean los datasets del job.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'La CLASS conecta el job con iniciadores específicos del JES que tienen recursos definidos.',
  ),
  60 => 
  array (
    'pregunta' => '¿Qué hace la utilidad IEBCOPY en JCL?',
    'opcion_a' => 'Copia, fusiona, selecciona o excluye miembros de datasets particionados (PDS/PDSE).',
    'opcion_b' => 'Genera copias de seguridad de datasets secuenciales en cinta magnética.',
    'opcion_c' => 'Copia registros entre datasets VSAM usando la interfaz de control SYSIN.',
    'opcion_d' => 'Compacta el directorio de un PDS eliminando entradas de miembros borrados.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'IEBCOPY COPY/SELECT/EXCLUDE gestiona miembros de PDS; también compacta con COMPRESS.',
  ),
  61 => 
  array (
    'pregunta' => '¿Cuál es el propósito principal del parámetro SPACE en JCL?',
    'opcion_a' => 'Definir el espacio en disco a asignar a un data set.',
    'opcion_b' => 'Añadir espacios en blanco al archivo.',
    'opcion_c' => 'Indicar la memoria RAM máxima del job.',
    'opcion_d' => 'Configurar los espacios de tabulación del código.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'SPACE asigna cilindros, tracks o bloques en disco.',
  ),
  62 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 1?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  63 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 2?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  64 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 3?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  65 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 4?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  66 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 5?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  67 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 6?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  68 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 7?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  69 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 8?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  70 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 9?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  71 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 10?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  72 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 11?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  73 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 12?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  74 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 13?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  75 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 14?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  76 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 15?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  77 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 16?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  78 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 17?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  79 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 18?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  80 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 19?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  81 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 20?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  82 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 21?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  83 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 22?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  84 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 23?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  85 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 24?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  86 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 25?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  87 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 26?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  88 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 27?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  89 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 28?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  90 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 29?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  91 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 30?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  92 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 31?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  93 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 32?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  94 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 33?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  95 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 34?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  96 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 35?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  97 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 36?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  98 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 37?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
  99 => 
  array (
    'pregunta' => '¿Qué cláusula de COBOL cierra un archivo 38?',
    'opcion_a' => 'CLOSE',
    'opcion_b' => 'END',
    'opcion_c' => 'EXIT',
    'opcion_d' => 'STOP',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CLOSE termina el procesamiento del archivo.',
  ),
);
}
