<?php
function get_informix_bank() {
    return array (
  0 => 
  array (
    'pregunta' => '¿Cuál es la extensión de un archivo fuente en Informix 4GL?',
    'opcion_a' => '.4gl',
    'opcion_b' => '.igl',
    'opcion_c' => '.ifx',
    'opcion_d' => '.sql',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Los programas 4GL se guardan con extensión .4gl y se compilan con el comando c4gl.',
  ),
  1 => 
  array (
    'pregunta' => '¿Cómo se declara una variable en Informix 4GL?',
    'opcion_a' => 'Con la cláusula DEFINE nombre tipo en la sección de declaraciones.',
    'opcion_b' => 'Con la palabra reservada VAR nombre AS tipo al inicio del módulo.',
    'opcion_c' => 'Con DECLARE nombre tipo antes de cada función del programa.',
    'opcion_d' => 'Con DIM nombre AS tipo dentro del bloque MAIN del programa.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'DEFINE es la palabra clave para variables locales y de módulo en Informix 4GL.',
  ),
  2 => 
  array (
    'pregunta' => '¿Qué hace la sentencia LET en Informix 4GL?',
    'opcion_a' => 'Asigna un valor a una variable: LET var = expresion.',
    'opcion_b' => 'Declara y asigna una variable en una sola línea de código.',
    'opcion_c' => 'Define una constante inmutable en el bloque de declaraciones.',
    'opcion_d' => 'Ejecuta una expresión SQL y guarda el resultado en una variable.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LET es el operador de asignación principal de 4GL; equivale a = en otros lenguajes.',
  ),
  3 => 
  array (
    'pregunta' => '¿Cuál es la estructura básica de un programa Informix 4GL?',
    'opcion_a' => 'DATABASE, DEFINE globales, MAIN...END MAIN con FUNCTIONs/REPORTs.',
    'opcion_b' => 'PROGRAM, VARIABLES, BEGIN...END con subrutinas CALL externas.',
    'opcion_c' => 'SCHEMA, DECLARATIONS, PROCEDURE...END PROCEDURE con cursores.',
    'opcion_d' => 'MODULE, DEFINE, BEGIN WORK...COMMIT con bloques EXCEPTION.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Un programa 4GL tiene DATABASE db, DEFINE vars, MAIN...END MAIN y FUNCTIONs opcionales.',
  ),
  4 => 
  array (
    'pregunta' => '¿Qué hace DATABASE nombre_bd al inicio de un programa 4GL?',
    'opcion_a' => 'Conecta el programa a la base de datos Informix especificada.',
    'opcion_b' => 'Crea una nueva base de datos con el nombre especificado en el servidor.',
    'opcion_c' => 'Declara el esquema de la base de datos para uso del precompilador.',
    'opcion_d' => 'Define los permisos de acceso a las tablas de la base de datos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'DATABASE conecta al servidor; puede usarse DISCONNECT para cerrar la conexión.',
  ),
  5 => 
  array (
    'pregunta' => '¿Cómo se ejecuta una consulta SELECT simple en Informix 4GL?',
    'opcion_a' => 'SELECT col INTO var FROM tabla WHERE condicion.',
    'opcion_b' => 'EXEC SQL SELECT col FROM tabla WHERE condicion INTO var.',
    'opcion_c' => 'FETCH nombre_cursor INTO var para cada SELECT del programa.',
    'opcion_d' => 'QUERY col FROM tabla WHERE condicion RETURNING var.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'El SELECT ... INTO var FROM ... es la forma directa para una sola fila en 4GL.',
  ),
  6 => 
  array (
    'pregunta' => '¿Qué hace la variable STATUS en Informix 4GL?',
    'opcion_a' => 'Contiene el código de error de la última operación de base de datos.',
    'opcion_b' => 'Indica el estado de la conexión actual con el servidor Informix.',
    'opcion_c' => 'Almacena el número de filas afectadas por el último SQL ejecutado.',
    'opcion_d' => 'Guarda el estado del formulario de pantalla actual del programa.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'STATUS = 0 indica éxito; NOTFOUND es 100; valores negativos son errores de Informix.',
  ),
  7 => 
  array (
    'pregunta' => '¿Qué es un cursor en Informix 4GL?',
    'opcion_a' => 'Un nombre que representa una consulta SELECT para iterar múltiples filas.',
    'opcion_b' => 'El puntero del ratón en las pantallas de interfaz de usuario 4GL.',
    'opcion_c' => 'Un tipo de variable especial para almacenar blobs de texto largo.',
    'opcion_d' => 'Un índice de tabla que optimiza la búsqueda de registros por clave.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'DECLARE cursor CURSOR FOR SELECT ...; se usa OPEN, FETCH y CLOSE para iterar filas.',
  ),
  8 => 
  array (
    'pregunta' => '¿Qué hace OPEN cursor_name en Informix 4GL?',
    'opcion_a' => 'Ejecuta la consulta y posiciona el cursor antes del primer registro.',
    'opcion_b' => 'Abre el archivo de definición del cursor almacenado en disco.',
    'opcion_c' => 'Conecta el cursor con la tabla y bloquea todos sus registros.',
    'opcion_d' => 'Abre una ventana de pantalla asociada al cursor de datos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'OPEN ejecuta el SELECT subyacente; FETCH recupera fila por fila hasta STATUS = NOTFOUND.',
  ),
  9 => 
  array (
    'pregunta' => '¿Cuál es la estructura básica para iterar sobre un cursor en 4GL?',
    'opcion_a' => 'OPEN c1; FETCH c1 INTO vars; WHILE STATUS=0 ... FETCH c1 INTO vars; END WHILE; CLOSE c1.',
    'opcion_b' => 'FOR EACH ROW IN c1 ... NEXT ROW; END FOR.',
    'opcion_c' => 'LOOP c1 FETCH INTO vars WHILE NOT EOF; END LOOP.',
    'opcion_d' => 'FOREACH cursor_name INTO vars ... CONTINUE FOREACH; END FOREACH.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'El patrón estándar: OPEN, FETCH, WHILE STATUS=0, procesar, FETCH, END WHILE, CLOSE.',
  ),
  10 => 
  array (
    'pregunta' => '¿Qué es SQLCA en Informix 4GL?',
    'opcion_a' => 'La estructura de comunicación SQL que contiene SQLCODE y mensajes de error.',
    'opcion_b' => 'La tabla del catálogo del sistema donde se almacenan los esquemas.',
    'opcion_c' => 'El archivo de configuración de la conexión con el servidor Informix.',
    'opcion_d' => 'El área de memoria compartida entre módulos de la aplicación 4GL.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'SQLCA (incluye SQLCODE, SQLERRM) se revisa tras cada operación SQL para detectar errores.',
  ),
  11 => 
  array (
    'pregunta' => '¿Qué hace la sentencia BEGIN WORK en Informix 4GL?',
    'opcion_a' => 'Inicia una transacción explícita en la base de datos Informix.',
    'opcion_b' => 'Marca el inicio del bloque de código principal del programa.',
    'opcion_c' => 'Abre una conexión nueva con el servidor de base de datos.',
    'opcion_d' => 'Inicia el procesamiento de un trabajo batch de múltiples registros.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'BEGIN WORK inicia la transacción; COMMIT WORK la confirma; ROLLBACK WORK la deshace.',
  ),
  12 => 
  array (
    'pregunta' => '¿Qué hace la sentencia COMMIT WORK en 4GL?',
    'opcion_a' => 'Confirma y hace permanentes todos los cambios de la transacción actual.',
    'opcion_b' => 'Guarda el estado del trabajo del usuario en la sesión activa.',
    'opcion_c' => 'Cierra la conexión con la base de datos de forma ordenada.',
    'opcion_d' => 'Envía los datos del formulario al servidor para su validación.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'COMMIT WORK finaliza la UOW haciendo permanentes los INSERTs, UPDATEs y DELETEs.',
  ),
  13 => 
  array (
    'pregunta' => '¿Para qué se usa la cláusula FOREACH en Informix 4GL?',
    'opcion_a' => 'Itera un SELECT automáticamente sin necesidad de OPEN/FETCH/CLOSE explícitos.',
    'opcion_b' => 'Itera sobre un array de variables definidas en el bloque de declaraciones.',
    'opcion_c' => 'Itera sobre las filas de un formulario de pantalla del usuario.',
    'opcion_d' => 'Itera sobre los módulos cargados en la sesión actual de 4GL.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'FOREACH SELECT col INTO var FROM tabla ... END FOREACH gestiona cursor internamente.',
  ),
  14 => 
  array (
    'pregunta' => '¿Qué hace INSERT en Informix 4GL?',
    'opcion_a' => 'Inserta un nuevo registro en la tabla de la base de datos Informix.',
    'opcion_b' => 'Inserta texto en el área de mensajes de la pantalla de usuario.',
    'opcion_c' => 'Agrega un elemento a un array dinámico de 4GL.',
    'opcion_d' => 'Inserta un módulo 4GL en el flujo de ejecución del programa.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'INSERT INTO tabla (cols) VALUES (vars) es igual que SQL estándar pero con variables 4GL.',
  ),
  15 => 
  array (
    'pregunta' => '¿Qué es un módulo GLOBALS en 4GL?',
    'opcion_a' => 'Un archivo .4gl que define variables compartidas entre múltiples programas.',
    'opcion_b' => 'Un módulo predefinido que contiene las funciones estándar del sistema.',
    'opcion_c' => 'La sección del programa donde se definen constantes de configuración.',
    'opcion_d' => 'Una librería de funciones de manejo de pantallas de usuario.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'GLOBALS "archivo.4gl" permite compartir variables de tipo GLOBALS entre módulos distintos.',
  ),
  16 => 
  array (
    'pregunta' => '¿Cómo se llama a una función en Informix 4GL?',
    'opcion_a' => 'CALL nombre_funcion(params) o LET var = nombre_funcion(params).',
    'opcion_b' => 'EXECUTE nombre_funcion WITH params RETURNING vars.',
    'opcion_c' => 'INVOKE nombre_funcion USING params INTO result.',
    'opcion_d' => 'RUN nombre_funcion(params) RETURNING result.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CALL para funciones sin retorno; LET var = funcion() para funciones con valor de retorno.',
  ),
  17 => 
  array (
    'pregunta' => '¿Qué hace DISPLAY en Informix 4GL?',
    'opcion_a' => 'Muestra un valor o mensaje en la pantalla del terminal del usuario.',
    'opcion_b' => 'Muestra un reporte de datos en la impresora predeterminada del sistema.',
    'opcion_c' => 'Define los atributos visuales del formulario de pantalla activo.',
    'opcion_d' => 'Visualiza el contenido de la tabla en formato tabular en pantalla.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'DISPLAY texto AT row, col muestra en pantalla; DISPLAY variable muestra su contenido.',
  ),
  18 => 
  array (
    'pregunta' => '¿Para qué sirve OPEN FORM en Informix 4GL?',
    'opcion_a' => 'Carga en memoria el formulario compilado .frm para su uso por el programa.',
    'opcion_b' => 'Abre el editor de formularios para modificar la pantalla en ejecución.',
    'opcion_c' => 'Inicia la conexión entre el formulario y la tabla de la base de datos.',
    'opcion_d' => 'Muestra el formulario en pantalla e inicia el modo de entrada de datos.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'OPEN FORM form_name FROM "archivo.frm"; luego DISPLAY FORM form_name lo muestra.',
  ),
  19 => 
  array (
    'pregunta' => '¿Qué hace INPUT en Informix 4GL?',
    'opcion_a' => 'Permite al usuario ingresar datos en los campos de un formulario de pantalla.',
    'opcion_b' => 'Lee datos de un archivo de texto de entrada para procesamiento batch.',
    'opcion_c' => 'Captura la entrada del teclado como caracteres individuales del usuario.',
    'opcion_d' => 'Recibe parámetros externos pasados al programa al momento de iniciarlo.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'INPUT BY NAME var1, var2 asocia variables con campos del formulario para captura de datos.',
  ),
  20 => 
  array (
    'pregunta' => '¿Cómo se define el tipo DATE en Informix 4GL?',
    'opcion_a' => 'DEFINE fecha DATE; almacena fechas en formato nativo de Informix.',
    'opcion_b' => 'DEFINE fecha CHAR(10); las fechas se guardan como cadena "YYYY-MM-DD".',
    'opcion_c' => 'DEFINE fecha INTEGER; las fechas se guardan como días desde 01/01/1900.',
    'opcion_d' => 'DEFINE fecha DATETIME YEAR TO DAY para compatibilidad con SQL estándar.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'DATE en 4GL es tipo nativo; se formatea con MDY(month,day,year) y TODAY retorna la actual.',
  ),
  21 => 
  array (
    'pregunta' => '¿Qué hace la función TODAY en Informix 4GL?',
    'opcion_a' => 'Retorna la fecha actual del sistema como tipo DATE.',
    'opcion_b' => 'Retorna la fecha y hora actual como tipo DATETIME.',
    'opcion_c' => 'Retorna el número de días transcurridos desde el inicio del año.',
    'opcion_d' => 'Retorna la fecha actual formateada como texto en formato YYYY-MM-DD.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'LET fecha = TODAY retorna DATE actual; CURRENT retorna DATETIME con hora.',
  ),
  22 => 
  array (
    'pregunta' => '¿Cómo se define un array en Informix 4GL?',
    'opcion_a' => 'DEFINE arr ARRAY[100] OF tipo_dato.',
    'opcion_b' => 'DEFINE arr tipo_dato[100].',
    'opcion_c' => 'DIM arr(100) AS tipo_dato.',
    'opcion_d' => 'CREATE ARRAY arr OF tipo_dato SIZE 100.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'ARRAY[n] define array estático; la indexación en 4GL empieza desde 1, no desde 0.',
  ),
  23 => 
  array (
    'pregunta' => '¿Qué hace ROLLBACK WORK en Informix 4GL?',
    'opcion_a' => 'Deshace todos los cambios de la transacción actual sin aplicarlos.',
    'opcion_b' => 'Regresa el cursor a la primera fila del resultado del SELECT.',
    'opcion_c' => 'Reinicia la aplicación desde el punto de inicio de sesión del usuario.',
    'opcion_d' => 'Cancela el formulario activo y regresa al menú principal.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'ROLLBACK WORK revierte INSERT/UPDATE/DELETE desde el último BEGIN WORK o COMMIT WORK.',
  ),
  24 => 
  array (
    'pregunta' => '¿Qué es NOTFOUND en Informix 4GL?',
    'opcion_a' => 'Una constante que equivale a 100 indicando que no se encontró ninguna fila.',
    'opcion_b' => 'Un tipo de error que indica que la tabla buscada no existe en la BD.',
    'opcion_c' => 'Una función que verifica si un registro existe antes de leerlo.',
    'opcion_d' => 'Un código de retorno de función que indica operación sin resultado.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'IF STATUS = NOTFOUND es el idiom 4GL para verificar que un SELECT no devolvió filas.',
  ),
  25 => 
  array (
    'pregunta' => '¿Para qué sirve el comando c4gl?',
    'opcion_a' => 'Compila archivos fuente .4gl a código objeto o ejecutable.',
    'opcion_b' => 'Conecta la aplicación 4GL al servidor de base de datos Informix.',
    'opcion_c' => 'Genera código fuente 4GL a partir de un esquema de base de datos.',
    'opcion_d' => 'Convierte programas ESQL/C a equivalentes en Informix 4GL.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'c4gl -o ejecutable fuente.4gl compila el programa; con múltiples archivos los enlaza.',
  ),
  26 => 
  array (
    'pregunta' => '¿Qué diferencia hay entre CHAR y VARCHAR en Informix?',
    'opcion_a' => 'CHAR tiene longitud fija rellena con espacios; VARCHAR ajusta al tamaño real.',
    'opcion_b' => 'VARCHAR solo acepta caracteres numéricos; CHAR acepta cualquier carácter.',
    'opcion_c' => 'CHAR es más eficiente para búsquedas; VARCHAR para inserciones masivas.',
    'opcion_d' => 'No hay diferencia; son alias del mismo tipo en versiones recientes.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'CHAR(n) siempre ocupa n bytes; VARCHAR(n) ocupa solo lo necesario hasta n bytes.',
  ),
  27 => 
  array (
    'pregunta' => '¿Qué hace la sentencia UPDATE en Informix 4GL?',
    'opcion_a' => 'Modifica los valores de columnas en filas existentes de una tabla.',
    'opcion_b' => 'Actualiza la definición de la tabla en el catálogo del sistema.',
    'opcion_c' => 'Refresca la pantalla del formulario con los datos más recientes de la BD.',
    'opcion_d' => 'Actualiza el índice de la tabla para optimizar las consultas posteriores.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE tabla SET col=val WHERE condicion es igual que SQL estándar en Informix 4GL.',
  ),
  28 => 
  array (
    'pregunta' => '¿Qué hace UPDATE WHERE CURRENT OF cursor en Informix 4GL?',
    'opcion_a' => 'Actualiza la fila actual apuntada por el cursor abierto con FOR UPDATE.',
    'opcion_b' => 'Actualiza todas las filas que coincidan con la posición actual del cursor.',
    'opcion_c' => 'Mueve el cursor a la siguiente fila y actualiza la anterior automáticamente.',
    'opcion_d' => 'Actualiza el cursor con la consulta SQL modificada en tiempo de ejecución.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'WHERE CURRENT OF es la forma eficiente de actualizar la fila exacta que FETCH recuperó.',
  ),
  29 => 
  array (
    'pregunta' => '¿Qué hace la función CLIPPED en Informix 4GL?',
    'opcion_a' => 'Elimina los espacios en blanco del final de una cadena CHAR.',
    'opcion_b' => 'Recorta una cadena al número de caracteres especificado.',
    'opcion_c' => 'Reemplaza los espacios en blanco dentro de la cadena por underscores.',
    'opcion_d' => 'Convierte la cadena a mayúsculas eliminando caracteres especiales.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'nombre CLIPPED retorna la cadena sin trailing spaces; esencial al concatenar campos CHAR.',
  ),
  30 => 
  array (
    'pregunta' => '¿Qué hace el operador || en Informix 4GL?',
    'opcion_a' => 'Concatena dos cadenas de texto: "Hola" || " " || "mundo".',
    'opcion_b' => 'Es el operador OR lógico para condiciones en sentencias IF.',
    'opcion_c' => 'Define el separador de campos en el archivo de importación de datos.',
    'opcion_d' => 'Declara un tipo de datos de cadena de longitud variable en la definición.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '|| es el operador de concatenación de cadenas tanto en SQL de Informix como en 4GL.',
  ),
  31 => 
  array (
    'pregunta' => '¿Cómo se pasan parámetros a un cursor dinámico en Informix 4GL?',
    'opcion_a' => 'DECLARE c CURSOR FOR SELECT ... WHERE col = ?; OPEN c USING var.',
    'opcion_b' => 'OPEN c WITH PARAMETERS (var1, var2) reemplaza los ? en el SELECT.',
    'opcion_c' => 'DEFINE PARAM c CURSOR FOR SELECT ... WHERE col = :var.',
    'opcion_d' => 'SET PARAM var FOR c; luego OPEN c aplica los parámetros automáticamente.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'El ? es el marcador de posición; OPEN cursor USING variable1, variable2 los sustituye.',
  ),
  32 => 
  array (
    'pregunta' => '¿Cómo se implementa un menú en Informix 4GL?',
    'opcion_a' => 'Con el bloque MENU "titulo" COMMAND "opcion" ... END MENU.',
    'opcion_b' => 'Con DISPLAY MENU FROM array de opciones al inicio del programa.',
    'opcion_c' => 'Con un formulario .per que contiene botones de menú en los campos.',
    'opcion_d' => 'Con la sentencia SHOW MENU nombre_menu RETURNING opcion_elegida.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'MENU...COMMAND "Agregar"... COMMAND "Salir"... END MENU crea el menú de texto estándar.',
  ),
  33 => 
  array (
    'pregunta' => '¿Qué hace CONSTRUCT en Informix 4GL?',
    'opcion_a' => 'Permite al usuario construir dinámicamente la cláusula WHERE de un SELECT.',
    'opcion_b' => 'Construye un nuevo objeto de base de datos a partir de una plantilla.',
    'opcion_c' => 'Inicializa y construye el formulario de pantalla cargando los datos iniciales.',
    'opcion_d' => 'Crea el SQL dinámico en una variable de cadena para su ejecución posterior.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'CONSTRUCT BY NAME clausula_where ON tabla.* permite búsquedas flexibles sin SQL manual.',
  ),
  34 => 
  array (
    'pregunta' => '¿Cómo se ejecuta SQL dinámico en Informix 4GL?',
    'opcion_a' => 'LET sql = "SELECT ..."; PREPARE stm FROM sql; EXECUTE stm [USING vars].',
    'opcion_b' => 'EXECUTE IMMEDIATE "SELECT..." INTO vars; es la forma directa.',
    'opcion_c' => 'DYNAMIC QUERY sql INTO vars ejecuta el SQL almacenado en la variable.',
    'opcion_d' => 'RUN SQL sql USING vars INTO vars es la instrucción de SQL dinámico.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'PREPARE compila el SQL dinámico; EXECUTE lo corre; DECLARE cursor FOR stm para SELECTs.',
  ),
  35 => 
  array (
    'pregunta' => '¿Cómo se define un registro (RECORD) en Informix 4GL?',
    'opcion_a' => 'DEFINE reg RECORD col1 CHAR(10), col2 INTEGER END RECORD.',
    'opcion_b' => 'DEFINE reg STRUCTURE {col1 CHAR(10), col2 INTEGER}.',
    'opcion_c' => 'CREATE RECORD reg (col1 CHAR(10), col2 INTEGER).',
    'opcion_d' => 'DEFINE reg LIKE tabla.* para replicar la estructura de una tabla.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'RECORD agrupa campos relacionados; DEFINE reg LIKE tabla.* copia el esquema de una tabla.',
  ),
  36 => 
  array (
    'pregunta' => '¿Qué hace DISPLAY ARRAY en Informix 4GL?',
    'opcion_a' => 'Muestra un array de registros en un scroll de pantalla navegable.',
    'opcion_b' => 'Imprime los elementos del array en la consola de texto del sistema.',
    'opcion_c' => 'Visualiza el contenido del array en formato de tabla en pantalla fija.',
    'opcion_d' => 'Envía el array al reporte de salida del módulo REPORT del programa.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'DISPLAY ARRAY muestra un subarray del array en un campo de scroll del formulario .per.',
  ),
  37 => 
  array (
    'pregunta' => '¿Qué hace la función MDY() en Informix 4GL?',
    'opcion_a' => 'Crea un valor DATE a partir de componentes numéricos mes, día, año.',
    'opcion_b' => 'Formatea una fecha en el orden Mes-Día-Año para su impresión.',
    'opcion_c' => 'Extrae los componentes mes, día y año de una fecha almacenada.',
    'opcion_d' => 'Convierte una cadena de texto en formato "MM/DD/YYYY" a tipo DATE.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'LET fecha = MDY(12, 31, 2024) crea una DATE; DATE() convierte un string a DATE.',
  ),
  38 => 
  array (
    'pregunta' => '¿Qué hace PAUSE en Informix 4GL?',
    'opcion_a' => 'Pausa la ejecución mostrando un mensaje hasta que el usuario presione una tecla.',
    'opcion_b' => 'Suspende el proceso actual por un número de segundos especificado.',
    'opcion_c' => 'Congela la pantalla actual mientras se procesa una consulta en background.',
    'opcion_d' => 'Hace una pausa entre transacciones para evitar saturar el servidor.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'PAUSE muestra "Press any key to continue." y espera; útil antes de regresar al menú.',
  ),
  39 => 
  array (
    'pregunta' => '¿Qué hace SET EXPLAIN ON en Informix?',
    'opcion_a' => 'Genera un archivo explain.out con el plan de acceso de cada SQL ejecutado.',
    'opcion_b' => 'Activa el modo de trazado SQL mostrando cada sentencia en el log.',
    'opcion_c' => 'Explica las opciones disponibles del onconfig al administrador.',
    'opcion_d' => 'Muestra estadísticas de uso de índices en tiempo real en pantalla.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'El plan en explain.out muestra si se usa índice, nested loops, hash join o full scan.',
  ),
  40 => 
  array (
    'pregunta' => '¿Qué es ONCONFIG en Informix y cuál es su función?',
    'opcion_a' => 'El archivo de configuración principal del servidor Informix Dynamic Server.',
    'opcion_b' => 'La herramienta de administración gráfica para configurar el servidor.',
    'opcion_c' => 'El programa que valida la configuración de la instancia Informix.',
    'opcion_d' => 'El registro del sistema operativo donde Informix guarda su configuración.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'onconfig contiene parámetros como DBSPACETEMP, BUFFERPOOL, LOCKS y MAX CONNECTIONS.',
  ),
  41 => 
  array (
    'pregunta' => '¿Cuándo se usa UPDATE STATISTICS en Informix?',
    'opcion_a' => 'Para actualizar las estadísticas de las tablas que el optimizador usa en los planes.',
    'opcion_b' => 'Para actualizar los índices de la tabla cuando hay fragmentación excesiva.',
    'opcion_c' => 'Para actualizar el catálogo del sistema con los últimos cambios del esquema.',
    'opcion_d' => 'Para forzar la reconstrucción del árbol B de los índices de la tabla.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'UPDATE STATISTICS FOR TABLE tabla activa el optimizador de consultas con datos reales.',
  ),
  42 => 
  array (
    'pregunta' => '¿Qué es la fragmentación (partitioning) en Informix y para qué sirve?',
    'opcion_a' => 'Distribuir filas de una tabla en múltiples dbspaces según una expresión.',
    'opcion_b' => 'Dividir el código fuente de la aplicación en múltiples módulos .4gl.',
    'opcion_c' => 'Particionar el log de transacciones en segmentos para mayor rendimiento.',
    'opcion_d' => 'Separar los índices de los datos en dbspaces diferentes para rendimiento.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'FRAGMENT BY RANGE o EXPRESSION distribuye datos; mejora parallelismo y mantenimiento.',
  ),
  43 => 
  array (
    'pregunta' => '¿Cómo se implementa una transacción distribuida en Informix 4GL?',
    'opcion_a' => 'Con conexiones múltiples y el uso de XA (Extended Architecture) con 2PC.',
    'opcion_b' => 'Con BEGIN DISTRIBUTED WORK ... COMMIT ALL que sincroniza múltiples BDs.',
    'opcion_c' => 'Con REMOTE BEGIN WORK en cada servidor y GLOBAL COMMIT al finalizar.',
    'opcion_d' => 'Con triggers en cada servidor que replican automáticamente los cambios.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'XA protocol con Two-Phase Commit permite ACID en transacciones entre múltiples instancias.',
  ),
  44 => 
  array (
    'pregunta' => '¿Cómo se hace backup online en Informix usando ontape?',
    'opcion_a' => 'ontape -s para backup nivel 0 (completo) mientras la BD está en línea.',
    'opcion_b' => 'ontape -b DATABASE nombre hace backup solo de la base especificada.',
    'opcion_c' => 'ontape -o archive genera el backup sin interrumpir las transacciones.',
    'opcion_d' => 'ontape -full hace backup completo requiriendo poner la instancia en modo quiesce.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'ontape -s -L 0 hace backup nivel 0 (full); -L 1 nivel 1 (incremental desde nivel 0).',
  ),
  45 => 
  array (
    'pregunta' => '¿Cómo se monitorean los bloqueos activos (locks) en Informix?',
    'opcion_a' => 'Con onstat -k que muestra todos los locks activos y las sesiones que los mantienen.',
    'opcion_b' => 'Con oncheck -cl que verifica la consistencia de los locks de la instancia.',
    'opcion_c' => 'Con SELECT * FROM syslocks en la base de datos sysmaster del servidor.',
    'opcion_d' => 'Con onstat -g ses que lista las sesiones con bloqueos activos pendientes.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'onstat -k muestra el tipo de lock (S, X, IS, IX), la tabla/fila y la sesión propietaria.',
  ),
  46 => 
  array (
    'pregunta' => '¿Para qué sirve oncheck en Informix y cuándo se usa?',
    'opcion_a' => 'Para verificar la consistencia e integridad de los datos y las páginas de disco.',
    'opcion_b' => 'Para comprobar la configuración del onconfig antes de arrancar el servidor.',
    'opcion_c' => 'Para verificar las conexiones activas y el uso de recursos de memoria.',
    'opcion_d' => 'Para comprobar si los backups de ontape son válidos y restaurables.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'oncheck -cd (datos) y -ci (índices) detectan corrupción de páginas en los dbspaces.',
  ),
  47 => 
  array (
    'pregunta' => '¿Qué es un dbspace en Informix y cómo se crea?',
    'opcion_a' => 'Un espacio de almacenamiento lógico mapeado a chunks de disco; se crea con onspaces -c.',
    'opcion_b' => 'Un directorio del sistema de archivos donde Informix guarda sus tablas.',
    'opcion_c' => 'Un área de memoria compartida para el buffer pool de la instancia.',
    'opcion_d' => 'Un espacio de base de datos temporal usado para ordenamiento de joins.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'onspaces -c -d nombre -p path_chunk -o offset -s size crea dbspace con su primer chunk.',
  ),
  48 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 1?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  49 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 2?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  50 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 3?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  51 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 4?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  52 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 5?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  53 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 6?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  54 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 7?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  55 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 8?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  56 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 9?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  57 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 10?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  58 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 11?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  59 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 12?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  60 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 13?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  61 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 14?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  62 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 15?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  63 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 16?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  64 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 17?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  65 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 18?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  66 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 19?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  67 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 20?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  68 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 21?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  69 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 22?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  70 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 23?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  71 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 24?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  72 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 25?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  73 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 26?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  74 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 27?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  75 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 28?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  76 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 29?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  77 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 30?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  78 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 31?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  79 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 32?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  80 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 33?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  81 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 34?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  82 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 35?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  83 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 36?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  84 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 37?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  85 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 38?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  86 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 39?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  87 => 
  array (
    'pregunta' => '¿Qué instrucción actualiza registros en Informix 40?',
    'opcion_a' => 'UPDATE',
    'opcion_b' => 'SET',
    'opcion_c' => 'MODIFY',
    'opcion_d' => 'CHANGE',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'UPDATE se usa para modificar datos existentes.',
  ),
  88 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 41',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 41 generada.',
  ),
  89 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 42',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 42 generada.',
  ),
  90 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 43',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 43 generada.',
  ),
  91 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 44',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 44 generada.',
  ),
  92 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 45',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 45 generada.',
  ),
  93 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 46',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 46 generada.',
  ),
  94 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 47',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 47 generada.',
  ),
  95 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 48',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 48 generada.',
  ),
  96 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 49',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 49 generada.',
  ),
  97 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 50',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 50 generada.',
  ),
  98 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 51',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 51 generada.',
  ),
  99 => 
  array (
    'pregunta' => 'Pregunta generada dinámica 52',
    'opcion_a' => 'Opcion A',
    'opcion_b' => 'Opcion B',
    'opcion_c' => 'Opcion C',
    'opcion_d' => 'Opcion D',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Explicación dinámica 52 generada.',
  ),
);
}
