<?php
// Banco oficial de 100 Preguntas de Java para Evaluación Técnica

function get_java_bank() {
    return array (
  0 => 
  array (
    'pregunta' => '¿Cuál de los siguientes identificadores NO corresponde a un tipo de dato primitivo en Java?',
    'opcion_a' => 'String',
    'opcion_b' => 'boolean',
    'opcion_c' => 'double',
    'opcion_d' => 'char',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'String es una clase de objeto inmutable ubicada en el paquete java.lang, mientras que double, boolean y char son tipos primitivos.',
    'tema' => 'java',
  ),
  1 => 
  array (
    'pregunta' => '¿Qué valor inicial por defecto asigna la JVM a un atributo booleano de instancia no inicializado?',
    'opcion_a' => 'null',
    'opcion_b' => 'false',
    'opcion_c' => 'true',
    'opcion_d' => '0',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => 'Los atributos primitivos de tipo boolean en las clases se inicializan automáticamente con false por la especificación de Java.',
    'tema' => 'java',
  ),
  2 => 
  array (
    'pregunta' => '¿Qué palabra reservada se utiliza en Java para implementar la herencia entre dos clases?',
    'opcion_a' => 'implements',
    'opcion_b' => 'inherits',
    'opcion_c' => 'extends',
    'opcion_d' => 'super',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Junior',
    'explicacion' => 'La palabra reservada extends establece herencia de clases, mientras que implements se utiliza exclusivamente para interfaces.',
    'tema' => 'java',
  ),
  3 => 
  array (
    'pregunta' => '¿Cuál es la firma exacta del método principal requerida para iniciar la ejecución de una aplicación estándar en Java?',
    'opcion_a' => 'protected static void start(String[] args)',
    'opcion_b' => 'public void main(String[] args)',
    'opcion_c' => 'public static int main(String args[])',
    'opcion_d' => 'public static void main(String[] args)',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Junior',
    'explicacion' => 'La JVM requiere obligatoriamente public static void main(String[] args) como punto de entrada ejecutable.',
    'tema' => 'java',
  ),
  4 => 
  array (
    'pregunta' => '¿Qué diferencia existe entre el operador == y equals() al comparar objetos?',
    'opcion_a' => '== compara referencias de memoria y equals() compara contenido o estado.',
    'opcion_b' => '== compara valores primitivos y equals() solo compara cadenas String.',
    'opcion_c' => 'equals() es más rápido porque omite la validación de tipos.',
    'opcion_d' => 'No existe ninguna diferencia funcional entre ambos en Java.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => '== valida si apuntan al mismo objeto en memoria; equals() compara equivalencia.',
    'tema' => 'java',
  ),
  5 => 
  array (
    'pregunta' => '¿Qué estructura de control de excepciones se ejecuta siempre, independientemente de si ocurrió un error o no?',
    'opcion_a' => 'catch',
    'opcion_b' => 'finally',
    'opcion_c' => 'throw',
    'opcion_d' => 'throws',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => 'El bloque finally se ejecuta de manera garantizada para tareas de limpieza como cerrar flujos o conexiones.',
    'tema' => 'java',
  ),
  6 => 
  array (
    'pregunta' => '¿Qué anotación principal de Spring Boot habilita la autoconfiguración, el escaneo de componentes y la configuración de propiedades?',
    'opcion_a' => '@EnableAutoConfiguration',
    'opcion_b' => '@ComponentScan',
    'opcion_c' => '@SpringBootApplication',
    'opcion_d' => '@Configuration',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Junior',
    'explicacion' => '@SpringBootApplication es una anotación compuesta que agrupa @Configuration, @EnableAutoConfiguration y @ComponentScan.',
    'tema' => 'java',
  ),
  7 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se utiliza para inyectar automáticamente dependencias gestionadas por el contenedor de inversión de control?',
    'opcion_a' => '@ResourceBean',
    'opcion_b' => '@Injectable',
    'opcion_c' => '@ComponentBind',
    'opcion_d' => '@Autowired',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Junior',
    'explicacion' => '@Autowired le indica al contenedor de Spring que resuelva e inyecte el bean colaborador requerido en el campo, setter o constructor.',
    'tema' => 'java',
  ),
  8 => 
  array (
    'pregunta' => '¿Cuál de las siguientes interfaces pertenece al framework de colecciones y NO permite elementos duplicados?',
    'opcion_a' => 'Set',
    'opcion_b' => 'Queue',
    'opcion_c' => 'List',
    'opcion_d' => 'Vector',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'La interfaz java.util.Set modela el concepto matemático de conjunto y no admite elementos duplicados.',
    'tema' => 'java',
  ),
  9 => 
  array (
    'pregunta' => '¿Qué anotación de Spring MVC se coloca a nivel de clase para crear controladores REST donde las respuestas se serializan automáticamente a JSON?',
    'opcion_a' => '@Controller',
    'opcion_b' => '@RestController',
    'opcion_c' => '@WebEndpoint',
    'opcion_d' => '@JsonController',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => '@RestController combina @Controller y @ResponseBody, haciendo que los retornos de los métodos se serialicen directamente en el cuerpo HTTP.',
    'tema' => 'java',
  ),
  10 => 
  array (
    'pregunta' => '¿Cuál es el modificador de acceso más restrictivo en Java?',
    'opcion_a' => 'protected',
    'opcion_b' => 'package-private (default)',
    'opcion_c' => 'private',
    'opcion_d' => 'public',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Junior',
    'explicacion' => 'El modificador private restringe la visibilidad del miembro únicamente al interior de la propia clase que lo define.',
    'tema' => 'java',
  ),
  11 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se utiliza comúnmente para marcar la capa de acceso a datos y permitir la traducción de excepciones de persistencia?',
    'opcion_a' => '@Service',
    'opcion_b' => '@DatabaseClient',
    'opcion_c' => '@Dao',
    'opcion_d' => '@Repository',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Junior',
    'explicacion' => '@Repository marca los componentes de acceso a datos y habilita la conversión automática de excepciones de persistencia a DataAccessException.',
    'tema' => 'java',
  ),
  12 => 
  array (
    'pregunta' => '¿Por qué se desaconseja concatenar String con el operador + dentro de bucles?',
    'opcion_a' => 'Crea múltiples objetos intermedios en memoria degradando el rendimiento.',
    'opcion_b' => 'Provoca un error de compilación en versiones modernas de Java.',
    'opcion_c' => 'Sobrescribe el valor de las variables locales en el stack.',
    'opcion_d' => 'Impide la ejecución del recolector de basura en el heap.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Cada concatenación genera un nuevo String; se recomienda usar StringBuilder.',
    'tema' => 'java',
  ),
  13 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se coloca sobre la capa que contiene la lógica de negocio de la aplicación?',
    'opcion_a' => '@Component',
    'opcion_b' => '@Service',
    'opcion_c' => '@Logic',
    'opcion_d' => '@BusinessModule',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => '@Service es una especialización semántica de @Component diseñada específicamente para encapsular la lógica de negocio.',
    'tema' => 'java',
  ),
  14 => 
  array (
    'pregunta' => '¿Qué método de la clase Object debe ser sobreescrito junto con equals() para mantener la coherencia en colecciones basadas en hash?',
    'opcion_a' => 'toString()',
    'opcion_b' => 'clone()',
    'opcion_c' => 'hashCode()',
    'opcion_d' => 'finalize()',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Junior',
    'explicacion' => 'El contrato general de Java establece que si dos objetos son iguales según equals(), deben devolver obligatoriamente el mismo hashCode().',
    'tema' => 'java',
  ),
  15 => 
  array (
    'pregunta' => '¿Qué palabra reservada impide que una clase sea extendida o que un método sea sobreescrito en Java?',
    'opcion_a' => 'static',
    'opcion_b' => 'abstract',
    'opcion_c' => 'const',
    'opcion_d' => 'final',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Junior',
    'explicacion' => 'Aplicar final a una clase evita que sea heredada, y aplicado a un método impide que clases hijas lo sobreescriban.',
    'tema' => 'java',
  ),
  16 => 
  array (
    'pregunta' => '¿Qué archivo de configuración estándar en formato clave-valor utiliza Spring Boot para configurar puertos y base de datos?',
    'opcion_a' => 'application.properties',
    'opcion_b' => 'pom.xml',
    'opcion_c' => 'beans.xml',
    'opcion_d' => 'server.config',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'application.properties (o application.yml) es el archivo estándar de propiedades de configuración que Spring Boot lee automáticamente.',
    'tema' => 'java',
  ),
  17 => 
  array (
    'pregunta' => '¿Qué interfaz funcional de java.util.function recibe un argumento y no retorna ningún resultado?',
    'opcion_a' => 'Function<T, R>',
    'opcion_b' => 'Consumer<T>',
    'opcion_c' => 'Predicate<T>',
    'opcion_d' => 'Supplier<T>',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => 'Consumer<T> define el método accept(T t), el cual consume el valor entregado y tiene retorno void.',
    'tema' => 'java',
  ),
  18 => 
  array (
    'pregunta' => '¿Qué tipo de excepción en Java deriva de RuntimeException y no requiere ser declarada obligatoriamente en la cláusula throws?',
    'opcion_a' => 'Checked Exception',
    'opcion_b' => 'Error de compilación',
    'opcion_c' => 'Unchecked Exception',
    'opcion_d' => 'Fatal Exception',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Junior',
    'explicacion' => 'Las subclases de RuntimeException y Error son excepciones no verificadas (unchecked) que el compilador no exige atrapar o declarar.',
    'tema' => 'java',
  ),
  19 => 
  array (
    'pregunta' => '¿Qué interfaz básica de Spring Data permite operaciones CRUD básicas sin necesidad de escribir consultas SQL manualmente?',
    'opcion_a' => 'EntityHandler',
    'opcion_b' => 'SqlTemplate',
    'opcion_c' => 'JdbcDaoSupport',
    'opcion_d' => 'CrudRepository',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Junior',
    'explicacion' => 'CrudRepository proporciona métodos genéricos como save(), findById(), findAll() y deleteById() listos para su uso.',
    'tema' => 'java',
  ),
  20 => 
  array (
    'pregunta' => '¿Qué estructura de datos almacena pares clave-valor en Java garantizando tiempo constante promedio O(1) en búsquedas?',
    'opcion_a' => 'HashMap',
    'opcion_b' => 'LinkedList',
    'opcion_c' => 'TreeMap',
    'opcion_d' => 'TreeSet',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'HashMap utiliza tablas hash con hashing de claves, ofreciendo complejidad O(1) en promedio para inserción y recuperación.',
    'tema' => 'java',
  ),
  21 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se utiliza para extraer variables de la ruta en una URL REST (ejemplo: /usuarios/{id})?',
    'opcion_a' => '@RequestParam',
    'opcion_b' => '@PathVariable',
    'opcion_c' => '@RequestHeader',
    'opcion_d' => '@RequestBody',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => '@PathVariable enlaza un segmento dinámico definido en la plantilla URI directamente a un parámetro del método del controlador.',
    'tema' => 'java',
  ),
  22 => 
  array (
    'pregunta' => '¿Cuál es el propósito de la palabra reservada super en el constructor de una subclase en Java?',
    'opcion_a' => 'Otorgar permisos administrativos al hilo de ejecución para omitir chequeos de seguridad.',
    'opcion_b' => 'Crear una segunda instancia aislada de la clase padre en un espacio de memoria independiente.',
    'opcion_c' => 'Invocar el constructor de la superclase para inicializar adecuadamente el estado heredado.',
    'opcion_d' => 'Indicar al recolector de basura que la instancia actual no debe ser destruida al salir del ámbito.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Junior',
    'explicacion' => 'super(...) invoca el constructor de la clase padre directa y debe ser obligatoriamente la primera sentencia del constructor hijo.',
    'tema' => 'java',
  ),
  23 => 
  array (
    'pregunta' => '¿Qué herramienta de construcción y gestión de dependencias en Java utiliza el archivo pom.xml?',
    'opcion_a' => 'Gradle',
    'opcion_b' => 'Ant',
    'opcion_c' => 'Make',
    'opcion_d' => 'Maven',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Junior',
    'explicacion' => 'Apache Maven utiliza el archivo Project Object Model (pom.xml) para la definición de dependencias, plugins y ciclo de construcción.',
    'tema' => 'java',
  ),
  24 => 
  array (
    'pregunta' => '¿Qué interfaz funcional recibe un objeto de entrada y retorna un valor booleano verdadero o falso?',
    'opcion_a' => 'Predicate<T>',
    'opcion_b' => 'Supplier<T>',
    'opcion_c' => 'Consumer<T>',
    'opcion_d' => 'UnaryOperator<T>',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Predicate<T> define el método test(T t) y se utiliza con frecuencia en operaciones de filtrado en Streams.',
    'tema' => 'java',
  ),
  25 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se coloca sobre un método en una clase @Configuration para que su valor retornado sea registrado como Bean?',
    'opcion_a' => '@Component',
    'opcion_b' => '@Bean',
    'opcion_c' => '@Service',
    'opcion_d' => '@Inject',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => '@Bean se coloca sobre métodos dentro de clases @Configuration para registrar manualmente una instancia en el ApplicationContext.',
    'tema' => 'java',
  ),
  26 => 
  array (
    'pregunta' => '¿Qué método de la interfaz java.lang.Runnable se debe implementar para definir la tarea que ejecutará un hilo?',
    'opcion_a' => 'start()',
    'opcion_b' => 'execute()',
    'opcion_c' => 'run()',
    'opcion_d' => 'init()',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Junior',
    'explicacion' => 'Runnable define el método abstracto public void run(), el cual contiene el código que ejecutará el hilo de ejecución.',
    'tema' => 'java',
  ),
  27 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se emplea para extraer los parámetros de consulta (query params) de una URL como ?pagina=2?',
    'opcion_a' => '@QueryString',
    'opcion_b' => '@PathVariable',
    'opcion_c' => '@MatrixVariable',
    'opcion_d' => '@RequestParam',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Junior',
    'explicacion' => '@RequestParam asocia los query parameters o parámetros de formulario multipart/urlencoded a variables en el controlador.',
    'tema' => 'java',
  ),
  28 => 
  array (
    'pregunta' => '¿Cuál de las siguientes afirmaciones describe con precisión a una clase abstracta en Java?',
    'opcion_a' => 'No puede ser instanciada directamente mediante el operador new y sirve como plantilla base.',
    'opcion_b' => 'No puede contener atributos ni métodos concretos con cuerpo implementado en su código.',
    'opcion_c' => 'Puede heredar simultáneamente de múltiples clases abstractas mediante herencia múltiple.',
    'opcion_d' => 'Todos sus métodos deben ser obligatoriamente declarados con el modificador public static.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'Las clases abstractas definen contratos y comportamientos compartidos, pero no pueden instanciarse directamente.',
    'tema' => 'java',
  ),
  29 => 
  array (
    'pregunta' => '¿Qué alcance (scope) tienen los Beans de Spring por defecto si no se especifica ninguna anotación @Scope adicional?',
    'opcion_a' => 'prototype',
    'opcion_b' => 'singleton',
    'opcion_c' => 'request',
    'opcion_d' => 'session',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => 'El alcance predeterminado de Spring es singleton, lo que significa que existe una única instancia compartida por contenedor IoC.',
    'tema' => 'java',
  ),
  30 => 
  array (
    'pregunta' => '¿Qué sentencia permite liberar recursos de manera automática al finalizar un bloque try sin requerir un bloque finally explícito?',
    'opcion_a' => 'try-catch-finally tradicional',
    'opcion_b' => 'synchronized block con monitor',
    'opcion_c' => 'try-with-resources con AutoCloseable',
    'opcion_d' => 'assert statement con validación',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Junior',
    'explicacion' => 'try-with-resources cierra automáticamente cualquier objeto que implemente java.lang.AutoCloseable al salir del bloque.',
    'tema' => 'java',
  ),
  31 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se utiliza para mapear peticiones HTTP de tipo POST a un método controlador específico?',
    'opcion_a' => '@GetMapping',
    'opcion_b' => '@PutMapping',
    'opcion_c' => '@ActionMapping',
    'opcion_d' => '@PostMapping',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Junior',
    'explicacion' => '@PostMapping es un atajo especializado para @RequestMapping(method = RequestMethod.POST).',
    'tema' => 'java',
  ),
  32 => 
  array (
    'pregunta' => '¿Cuál es la función del recolector de basura (Garbage Collector) en la máquina virtual de Java?',
    'opcion_a' => 'Liberar automáticamente la memoria del Heap ocupada por objetos que ya no son alcanzables.',
    'opcion_b' => 'Compilar el código fuente a bytecode optimizado antes de ejecutar la aplicación.',
    'opcion_c' => 'Verificar las firmas criptográficas de los archivos .jar para evitar inyecciones maliciosas.',
    'opcion_d' => 'Controlar el acceso a los registros del procesador y sincronizar la caché L1 de hardware.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Junior',
    'explicacion' => 'El Garbage Collector rastrea referencias en el Heap y reclama la memoria de objetos que ya no tienen referencias activas.',
    'tema' => 'java',
  ),
  33 => 
  array (
    'pregunta' => '¿Qué anotación en Spring se coloca sobre un parámetro de método para deserializar el cuerpo JSON de la petición HTTP a un objeto Java?',
    'opcion_a' => '@ResponseBody',
    'opcion_b' => '@RequestBody',
    'opcion_c' => '@ModelAttribute',
    'opcion_d' => '@RequestPart',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Junior',
    'explicacion' => '@RequestBody le indica a Spring que lea el cuerpo HTTP entrante y utilice HttpMessageConverter (como Jackson) para convertirlo a objeto.',
    'tema' => 'java',
  ),
  34 => 
  array (
    'pregunta' => '¿Qué garantiza declarar una variable compartida como volatile en Java?',
    'opcion_a' => 'Garantiza atomicidad completa en operaciones de incremento.',
    'opcion_b' => 'Bloquea el hilo actual durante la lectura de la variable.',
    'opcion_c' => 'Garantiza visibilidad directa de cambios entre hilos en memoria.',
    'opcion_d' => 'Almacena la variable permanentemente en el pool de constantes.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'volatile asegura que las lecturas y escrituras vayan a memoria principal.',
    'tema' => 'java',
  ),
  35 => 
  array (
    'pregunta' => '¿Qué anotación declarativa de Spring administra transacciones automáticamente abriendo, confirmando o revirtiendo la sesión?',
    'opcion_a' => '@AtomicOperation',
    'opcion_b' => '@RollbackOnFail',
    'opcion_c' => '@TransactionManaged',
    'opcion_d' => '@Transactional',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@Transactional delega en el TransactionManager de Spring la apertura, commit o rollback ante RuntimeExceptions.',
    'tema' => 'java',
  ),
  36 => 
  array (
    'pregunta' => '¿Por qué se prefiere la inyección por constructor sobre la inyección por campo?',
    'opcion_a' => 'Facilita la inmutabilidad, el testing unitario y evita dependencias nulas.',
    'opcion_b' => 'Incrementa la velocidad de compilación de los controladores web.',
    'opcion_c' => 'Elimina la necesidad de definir anotaciones en clases de configuración.',
    'opcion_d' => 'Permite crear beans sin necesidad de instanciar la clase en el heap.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'La inyección por constructor promueve beans inmutables y tests sin reflection.',
    'tema' => 'java',
  ),
  37 => 
  array (
    'pregunta' => 'En el API de Streams de Java, ¿cuál de las siguientes operaciones es una operación TERMINAL que produce un resultado y cierra el stream?',
    'opcion_a' => 'filter()',
    'opcion_b' => 'collect()',
    'opcion_c' => 'map()',
    'opcion_d' => 'distinct()',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'collect() es una operación terminal que procesa los elementos del flujo y los empaqueta en una colección final, dando fin al Stream.',
    'tema' => 'java',
  ),
  38 => 
  array (
    'pregunta' => '¿Qué nivel de propagación transaccional en Spring ejecuta el método en una transacción física independiente y suspende la transacción actual si existía?',
    'opcion_a' => 'Propagation.REQUIRED',
    'opcion_b' => 'Propagation.NESTED',
    'opcion_c' => 'Propagation.REQUIRES_NEW',
    'opcion_d' => 'Propagation.SUPPORTS',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'REQUIRES_NEW siempre suspende cualquier transacción externa preexistente e inicia una transacción física independiente y aislada.',
    'tema' => 'java',
  ),
  39 => 
  array (
    'pregunta' => '¿Cómo gestiona la concurrencia interna la clase ConcurrentHashMap en comparación con Hashtable?',
    'opcion_a' => 'Bloquea el mapa completo en cada lectura y escritura mediante un monitor global sincronizado.',
    'opcion_b' => 'Delega la persistencia en archivos temporales del sistema operativo para evitar colisiones.',
    'opcion_c' => 'Copia la tabla completa en cada operación de escritura similar a CopyOnWriteArrayList.',
    'opcion_d' => 'Permite lecturas sin bloqueo y utiliza bloqueos segmentados o CAS a nivel de cubeta individual (bucket).',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'ConcurrentHashMap permite lecturas concurrentes sin cerrojo y limita los bloqueos a la cubeta específica que se modifica con CAS y locks finos.',
    'tema' => 'java',
  ),
  40 => 
  array (
    'pregunta' => '¿Qué anotación de Spring Data JPA permite escribir consultas personalizadas en sintaxis JPQL o SQL nativo?',
    'opcion_a' => '@Query',
    'opcion_b' => '@SelectQuery',
    'opcion_c' => '@JpaMapping',
    'opcion_d' => '@NativeSql',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@Query se coloca sobre métodos de interfaces de repositorio para definir consultas JPQL o consultas SQL nativas con nativeQuery = true.',
    'tema' => 'java',
  ),
  41 => 
  array (
    'pregunta' => '¿Qué método del ciclo de vida de un Bean de Spring se ejecuta inmediatamente después de que el contenedor ha inyectado todas las dependencias?',
    'opcion_a' => '@PreDestroy',
    'opcion_b' => '@PostConstruct',
    'opcion_c' => '@BeanInit',
    'opcion_d' => '@OnLoaded',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'La anotación @PostConstruct de javax.annotation / jakarta.annotation marca el método de inicialización que corre tras la inyección de dependencias.',
    'tema' => 'java',
  ),
  42 => 
  array (
    'pregunta' => '¿Cuál es la diferencia principal entre map() y flatMap() en Java Streams?',
    'opcion_a' => 'map() es una operación terminal y flatMap() es intermedia.',
    'opcion_b' => 'flatMap() filtra elementos mientras que map() los ordena de forma natural.',
    'opcion_c' => 'map() transforma elementos 1 a 1 y flatMap() aplana streams anidados.',
    'opcion_d' => 'flatMap() solo funciona sobre colecciones inmutables de tipo Set.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'flatMap transforma cada elemento en un stream y luego aplana los resultados.',
    'tema' => 'java',
  ),
  43 => 
  array (
    'pregunta' => '¿Qué módulo de Spring Boot proporciona endpoints listos para producción para monitorear métricas, salud (health) e información de la aplicación?',
    'opcion_a' => 'Spring Boot DevTools',
    'opcion_b' => 'Spring Boot Inspector',
    'opcion_c' => 'Spring Boot Admin',
    'opcion_d' => 'Spring Boot Actuator',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Spring Boot Actuator expone endpoints como /actuator/health, /actuator/metrics y /actuator/info para monitoreo operativo.',
    'tema' => 'java',
  ),
  44 => 
  array (
    'pregunta' => '¿Cuál es el propósito principal de Optional<T> como retorno en Java?',
    'opcion_a' => 'Expresar explícitamente la posible ausencia de un valor y evitar NPE.',
    'opcion_b' => 'Reemplazar el uso de colecciones vacías como listas y conjuntos.',
    'opcion_c' => 'Serializar objetos de forma binaria en sistemas distribuidos.',
    'opcion_d' => 'Optimizar el uso de memoria RAM reduciendo el tamaño del objeto.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Optional comunica a quien invoca que el resultado puede no estar presente.',
    'tema' => 'java',
  ),
  45 => 
  array (
    'pregunta' => '¿Qué anotación se utiliza en Spring para capturar excepciones globales y centralizar el manejo de errores en toda la aplicación REST?',
    'opcion_a' => '@ErrorHandler',
    'opcion_b' => '@ControllerAdvice (o @RestControllerAdvice)',
    'opcion_c' => '@GlobalCatch',
    'opcion_d' => '@ExceptionFilter',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@RestControllerAdvice combina @ControllerAdvice con @ResponseBody para manejar excepciones transversalmente con métodos @ExceptionHandler.',
    'tema' => 'java',
  ),
  46 => 
  array (
    'pregunta' => '¿Qué estructura de hilos de java.util.concurrent se debe utilizar para ejecutar tareas concurrentes reutilizando un grupo fijo de hilos?',
    'opcion_a' => 'ThreadFactory',
    'opcion_b' => 'ForkJoinTask',
    'opcion_c' => 'Executors.newFixedThreadPool(n)',
    'opcion_d' => 'CompletableFuturePool',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'newFixedThreadPool crea un ExecutorService con un número constante de hilos reutilizables y una cola de tareas compartida.',
    'tema' => 'java',
  ),
  47 => 
  array (
    'pregunta' => '¿Qué anotación de Spring permite inyectar valores desde archivos de propiedades o variables de entorno mediante expresiones SpEL como "${app.servidor.url}"?',
    'opcion_a' => '@PropertySource',
    'opcion_b' => '@ConfigurationProperties',
    'opcion_c' => '@InjectValue',
    'opcion_d' => '@Value',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@Value("${propiedad}") inyecta valores de configuración directamente en variables de instancia en tiempo de construcción del Bean.',
    'tema' => 'java',
  ),
  48 => 
  array (
    'pregunta' => '¿Cómo utiliza Spring los Proxies dinámicos en clases con anotaciones como @Transactional?',
    'opcion_a' => 'Intercepta llamadas a métodos para aplicar lógica transversal como transacciones.',
    'opcion_b' => 'Compila el código Java directamente a lenguaje ensamblador de la máquina.',
    'opcion_c' => 'Sustituye la máquina virtual por un contenedor nativo en memoria.',
    'opcion_d' => 'Desactiva el recolector de basura durante la ejecución del método.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Los proxies interceptan la invocación para iniciar y confirmar transacciones.',
    'tema' => 'java',
  ),
  49 => 
  array (
    'pregunta' => '¿Qué estrategia de @GeneratedValue delega el ID a una columna AUTO_INCREMENT de MySQL?',
    'opcion_a' => 'GenerationType.SEQUENCE',
    'opcion_b' => 'GenerationType.IDENTITY',
    'opcion_c' => 'GenerationType.AUTO',
    'opcion_d' => 'GenerationType.TABLE',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'IDENTITY utiliza columnas autonuméricas nativas del motor relacional.',
    'tema' => 'java',
  ),
  50 => 
  array (
    'pregunta' => '¿Qué excepción lanza un Iterator fail-fast si se modifica la colección concurrentemente?',
    'opcion_a' => 'IllegalStateException',
    'opcion_b' => 'UnsupportedOperationException',
    'opcion_c' => 'ConcurrentModificationException',
    'opcion_d' => 'IndexOutOfBoundsException',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Los iteradores fail-fast detectan cambios estructurales y lanzan la excepción.',
    'tema' => 'java',
  ),
  51 => 
  array (
    'pregunta' => '¿Qué anotación de Spring habilita el almacenamiento en caché de resultados de métodos para evitar consultas repetitivas a la base de datos?',
    'opcion_a' => '@CacheMemo',
    'opcion_b' => '@StoreResult',
    'opcion_c' => '@Remember',
    'opcion_d' => '@Cacheable',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@Cacheable indica a Spring que almacene en el caché configurado el resultado del método asociado a los argumentos provistos.',
    'tema' => 'java',
  ),
  52 => 
  array (
    'pregunta' => '¿Cuál es la diferencia entre CompletableFuture y el antiguo Future<T> introducido en Java 5?',
    'opcion_a' => 'CompletableFuture permite componer cadenas asíncronas no bloqueantes con callbacks como thenApply() y manejar excepciones funcionalmente.',
    'opcion_b' => 'Future permite ejecutar múltiples hilos simultáneos, mientras que CompletableFuture se ejecuta en un solo hilo síncrono.',
    'opcion_c' => 'CompletableFuture solo funciona con sistemas de archivos y no admite conexiones de red concurrentes.',
    'opcion_d' => 'No existen diferencias en la API excepto el soporte para serialización en formatos XML.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'CompletableFuture introduce composición funcional asíncrona, combinación de futuros y callbacks sin requerir llamadas bloqueantes a get().',
    'tema' => 'java',
  ),
  53 => 
  array (
    'pregunta' => '¿Qué interfaz de Spring Security se implementa típicamente para cargar los datos del usuario desde la base de datos durante la autenticación?',
    'opcion_a' => 'AuthenticationManager',
    'opcion_b' => 'UserDetailsService',
    'opcion_c' => 'SecurityFilterChain',
    'opcion_d' => 'PasswordEncoder',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'UserDetailsService define el método loadUserByUsername(String username) para retornar la entidad UserDetails necesaria para autenticar.',
    'tema' => 'java',
  ),
  54 => 
  array (
    'pregunta' => '¿Qué mecanismo de carga utiliza la anotación @OneToMany de JPA por defecto según la especificación?',
    'opcion_a' => 'FetchType.EAGER (carga inmediata)',
    'opcion_b' => 'FetchType.PARALLEL (carga asíncrona en hilo secundario)',
    'opcion_c' => 'FetchType.LAZY (carga perezosa bajo demanda)',
    'opcion_d' => 'FetchType.BATCH (carga agrupada en bloques fijos)',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Por especificación JPA, las relaciones a colección (@OneToMany y @ManyToMany) usan por defecto FetchType.LAZY para evitar sobrecarga.',
    'tema' => 'java',
  ),
  55 => 
  array (
    'pregunta' => '¿Qué clase de Java 8 se debe preferir para manejar fechas y horas con huso horario de forma inmutable?',
    'opcion_a' => 'java.util.Date',
    'opcion_b' => 'java.util.Calendar',
    'opcion_c' => 'java.sql.Timestamp',
    'opcion_d' => 'java.time.ZonedDateTime',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'ZonedDateTime en java.time es inmutable, thread-safe y almacena fecha, hora y reglas de zona horaria (ZoneId).',
    'tema' => 'java',
  ),
  56 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se utiliza para condicionar la creación de un Bean solo si una propiedad específica está presente y activa?',
    'opcion_a' => '@ConditionalOnProperty',
    'opcion_b' => '@RequiresProperty',
    'opcion_c' => '@IfConfigured',
    'opcion_d' => '@PropertyMatch',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@ConditionalOnProperty permite registrar beans condicionalmente en función del valor o presencia de una propiedad en el entorno.',
    'tema' => 'java',
  ),
  57 => 
  array (
    'pregunta' => '¿Cómo resuelve Java el conflicto si dos interfaces definen el mismo método default?',
    'opcion_a' => 'Ejecuta aleatoriamente la implementación de cualquiera de las interfaces.',
    'opcion_b' => 'Obliga a la clase implementadora a sobrescribir el método en conflicto.',
    'opcion_c' => 'Ignora ambos métodos y genera un error silencioso en tiempo de ejecución.',
    'opcion_d' => 'Hereda siempre el método de la interfaz declarada en primer lugar.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'El compilador exige desambiguar implementando explícitamente el método.',
    'tema' => 'java',
  ),
  58 => 
  array (
    'pregunta' => '¿Qué anotación de Spring Data JPA se coloca sobre un método del repositorio para indicar que ejecuta una consulta UPDATE o DELETE?',
    'opcion_a' => '@QueryChange',
    'opcion_b' => '@TransactionalWrite',
    'opcion_c' => '@Modifying',
    'opcion_d' => '@UpdateOperation',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@Modifying le indica a Spring Data JPA que la consulta ejecutada altera el estado de la base de datos (DML) y no es un simple SELECT.',
    'tema' => 'java',
  ),
  59 => 
  array (
    'pregunta' => '¿Qué patrón estructural utiliza la clase java.lang.StringBuilder para encadenar llamadas como .append("a").append("b")?',
    'opcion_a' => 'Factory Pattern',
    'opcion_b' => 'Singleton Pattern',
    'opcion_c' => 'Observer Pattern',
    'opcion_d' => 'Builder / Fluent Interface Pattern',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'StringBuilder retorna this en cada llamada de método append(), implementando una interfaz fluida del patrón Builder.',
    'tema' => 'java',
  ),
  60 => 
  array (
    'pregunta' => '¿Qué componente central de Spring Web MVC intercepta todas las peticiones HTTP entrantes y las despacha a los controladores registrados?',
    'opcion_a' => 'DispatcherServlet',
    'opcion_b' => 'ContextLoaderListener',
    'opcion_c' => 'FilterSecurityInterceptor',
    'opcion_d' => 'HandlerMappingEngine',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'DispatcherServlet actúa como Front Controller en la arquitectura de Spring Web MVC, coordinando handlers, controladores y vistas.',
    'tema' => 'java',
  ),
  61 => 
  array (
    'pregunta' => '¿Qué retorna el método add() de un Set cuando se intenta agregar un elemento repetido?',
    'opcion_a' => 'Lanza un DuplicateKeyException al detectar la colisión.',
    'opcion_b' => 'Retorna false y el conjunto permanece sin modificaciones.',
    'opcion_c' => 'Retorna true y sobrescribe el elemento ya existente.',
    'opcion_d' => 'Elimina todos los elementos previos del conjunto.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Set.add() retorna false si el elemento ya existe según equals() y hashCode().',
    'tema' => 'java',
  ),
  62 => 
  array (
    'pregunta' => '¿Qué anotación de Spring Boot permite vincular de forma tipada un prefijo completo de propiedades YAML o properties a una clase Java?',
    'opcion_a' => '@EnvBinding',
    'opcion_b' => '@PropertyMapping',
    'opcion_c' => '@ConfigurationProperties',
    'opcion_d' => '@ValueHolder',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@ConfigurationProperties(prefix = "app") enlaza jerárquicamente grupos de propiedades de configuración a campos de un bean con validación.',
    'tema' => 'java',
  ),
  63 => 
  array (
    'pregunta' => '¿Cuál es la función del método intern() en la clase String de Java?',
    'opcion_a' => 'Generar una copia encriptada de la cadena para almacenamiento en variables locales.',
    'opcion_b' => 'Traducir el contenido de la cadena a caracteres internacionales UTF-16 en tiempo de ejecución.',
    'opcion_c' => 'Limpiar los espacios en blanco iniciales y finales de la cadena de forma destructiva.',
    'opcion_d' => 'Colocar o recuperar la instancia de cadena dentro del String Constant Pool de la JVM para compartir memoria.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'intern() garantiza que todas las cadenas con el mismo contenido textual compartan la misma referencia en el String Pool.',
    'tema' => 'java',
  ),
  64 => 
  array (
    'pregunta' => '¿Qué sucede cuando se anota un método con @Async en Spring?',
    'opcion_a' => 'El método se ejecuta de forma asíncrona en un hilo separado gestionado por un TaskExecutor sin bloquear al invocador.',
    'opcion_b' => 'La base de datos ejecuta la consulta en modo no bloqueante mediante WebClient exclusivamente.',
    'opcion_c' => 'La máquina virtual detiene los procesos en segundo plano para dedicar el 100% de la CPU al método.',
    'opcion_d' => 'El método se convierte obligatoriamente en una función recursiva con control de pila.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@Async delega la ejecución del método a un TaskExecutor en un hilo independiente, requiriendo tener activa @EnableAsync.',
    'tema' => 'java',
  ),
  65 => 
  array (
    'pregunta' => '¿Cuál es la forma idónea de manejar checked exceptions dentro de un map() en Streams?',
    'opcion_a' => 'Usar throws directamente en la expresión lambda del stream.',
    'opcion_b' => 'Envolver la lógica en un try-catch o una función envolvente de tipo wrapper.',
    'opcion_c' => 'Desactivar el chequeo de excepciones con la directiva @IgnoreException.',
    'opcion_d' => 'Castear el Stream a un objeto de tipo ParallelStream.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Semi-Senior',
    'explicacion' => 'Las lambdas funcionales de Streams no admiten checked exceptions sin manejo.',
    'tema' => 'java',
  ),
  66 => 
  array (
    'pregunta' => '¿Qué anotación de Spring se emplea para resolver ambigüedad cuando existen dos o más Beans del mismo tipo candidatos para inyección?',
    'opcion_a' => '@SpecificBean',
    'opcion_b' => '@Discriminator',
    'opcion_c' => '@Qualifier',
    'opcion_d' => '@UniqueCandidate',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Semi-Senior',
    'explicacion' => '@Qualifier("nombreBean") especifica exactamente qué bean debe ser inyectado cuando existen múltiples alternativas del mismo tipo.',
    'tema' => 'java',
  ),
  67 => 
  array (
    'pregunta' => '¿Cómo divide la memoria del Heap el recolector de basura G1 de la JVM?',
    'opcion_a' => 'En dos únicas áreas monolíticas contiguas de tamaño fijo e inalterable.',
    'opcion_b' => 'En pilas dinámicas asignadas exclusivamente a cada hilo del sistema.',
    'opcion_c' => 'En una única región continua sin división generacional.',
    'opcion_d' => 'En múltiples regiones independientes de igual tamaño asignadas por roles.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'G1 divide el heap en regiones iguales (1MB a 32MB) que actúan como Eden/Old.',
    'tema' => 'java',
  ),
  68 => 
  array (
    'pregunta' => '¿Por qué @Transactional falla al invocarse desde otro método de la misma clase?',
    'opcion_a' => 'La llamada interna a this omite el proxy transaccional de Spring.',
    'opcion_b' => 'Spring bloquea las transacciones recursivas por motivos de seguridad.',
    'opcion_c' => 'La conexión a la base de datos se cierra automáticamente al primer paso.',
    'opcion_d' => 'Los métodos públicos de la misma clase comparten el mismo hilo JDBC.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Al invocar internamente a this, la llamada no pasa por el proxy interceptor.',
    'tema' => 'java',
  ),
  69 => 
  array (
    'pregunta' => '¿Qué solución resuelve eficazmente el problema de N+1 queries en JPA?',
    'opcion_a' => 'Cambiar la estrategia de carga de relaciones de EAGER a LAZY.',
    'opcion_b' => 'Utilizar JOIN FETCH en consultas JPQL o definir Entity Graphs.',
    'opcion_c' => 'Desactivar el contexto de persistencia en cada consulta SELECT.',
    'opcion_d' => 'Configurar la base de datos con aislamiento TRANSACTION_NONE.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Senior',
    'explicacion' => 'JOIN FETCH carga la entidad y sus asociaciones en una única consulta SQL.',
    'tema' => 'java',
  ),
  70 => 
  array (
    'pregunta' => '¿Qué asegura la regla Happens-Before en el modelo de memoria de Java (JMM)?',
    'opcion_a' => 'Que los hilos finalicen su ejecución en el orden en que fueron creados.',
    'opcion_b' => 'Que la memoria no sufra nunca errores de desbordamiento OutOfMemoryError.',
    'opcion_c' => 'Que la escritura de un hilo sea visible de forma predecible por otro hilo.',
    'opcion_d' => 'Que la recolección de basura ocurra antes de instanciar nuevos objetos.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Senior',
    'explicacion' => 'Happens-before garantiza coherencia y visibilidad entre operaciones multihilo.',
    'tema' => 'java',
  ),
  71 => 
  array (
    'pregunta' => '¿Cuál es el rol de SecurityFilterChain en Spring Security 6?',
    'opcion_a' => 'Conectarse directamente al servidor LDAP para validar usuarios.',
    'opcion_b' => 'Generar tablas de roles y permisos automáticamente en la base.',
    'opcion_c' => 'Compilar reglas de seguridad a nivel de bytecode en el arranque.',
    'opcion_d' => 'Definir y ordenar la cadena de filtros de autenticación y autorización.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'SecurityFilterChain especifica los filtros HTTP aplicados a cada endpoint.',
    'tema' => 'java',
  ),
  72 => 
  array (
    'pregunta' => '¿Qué optimización permite el Escape Analysis en el compilador JIT de Java?',
    'opcion_a' => 'Asignar objetos en el Stack en lugar del Heap y eliminar sincronizaciones.',
    'opcion_b' => 'Comprimir el código fuente para reducir el tamaño del archivo JAR.',
    'opcion_c' => 'Cerrar sockets de red que no se utilicen tras un periodo de inactividad.',
    'opcion_d' => 'Descargar clases no utilizadas para liberar el Metaspace de la JVM.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Si un objeto no escapa del método, se puede scalarizar o ubicar en el stack.',
    'tema' => 'java',
  ),
  73 => 
  array (
    'pregunta' => '¿Qué excepción lanza JPA cuando falla un bloqueo optimista con @Version?',
    'opcion_a' => 'ConcurrentUpdateException',
    'opcion_b' => 'OptimisticLockException',
    'opcion_c' => 'StaleDataSQLException',
    'opcion_d' => 'TransactionRolledBackException',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Senior',
    'explicacion' => 'Se lanza OptimisticLockException si la versión en DB difiere de la cargada.',
    'tema' => 'java',
  ),
  74 => 
  array (
    'pregunta' => '¿Cuál es la principal ventaja de los Virtual Threads en Java 21?',
    'opcion_a' => 'Multiplican la velocidad de cálculo intensivo de la CPU por diez.',
    'opcion_b' => 'Reemplazan el recolector de basura tradicional por uno en tiempo real.',
    'opcion_c' => 'Permiten millones de hilos ligeros bloqueantes en I/O con mínimo consumo.',
    'opcion_d' => 'Eliminan la necesidad de sincronizar variables compartidas entre hilos.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Senior',
    'explicacion' => 'Los hilos virtuales se montan en carrier threads al bloquearse por I/O.',
    'tema' => 'java',
  ),
  75 => 
  array (
    'pregunta' => '¿Por qué una colección estática no limpiada provoca fuga de memoria en Java?',
    'opcion_a' => 'Porque el compilador javac prohíbe liberar memoria estática.',
    'opcion_b' => 'Porque la JVM bloquea la recolección en variables final.',
    'opcion_c' => 'Porque las variables estáticas se almacenan en el registro del CPU.',
    'opcion_d' => 'Porque sus objetos permanecen alcanzables desde la raíz GC Root.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'Los objetos referenciados por clases cargadas (GC roots) nunca son recolectados.',
    'tema' => 'java',
  ),
  76 => 
  array (
    'pregunta' => '¿Qué estado adopta un Circuit Breaker cuando detecta una alta tasa de fallos?',
    'opcion_a' => 'OPEN: rechaza llamadas inmediatas sin consultar al servicio remoto.',
    'opcion_b' => 'CLOSED: duplica el ancho de banda para compensar la latencia.',
    'opcion_c' => 'HALF-OPEN: apaga el contenedor de Spring Boot para reiniciarlo.',
    'opcion_d' => 'LOCKED: bloquea el hilo principal hasta recibir una respuesta HTTP.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'El estado OPEN corta el flujo para dar tiempo de recuperación al servicio.',
    'tema' => 'java',
  ),
  77 => 
  array (
    'pregunta' => '¿Cuál es el objetivo principal del recolector ZGC en la JVM de Java?',
    'opcion_a' => 'Minimizar el uso de memoria RAM a expensas de pausas prolongadas.',
    'opcion_b' => 'Garantizar tiempos de pausa sub-milisegundos en heaps de hasta 16TB.',
    'opcion_c' => 'Desactivar la compilación JIT para mejorar el arranque en frío.',
    'opcion_d' => 'Evitar la fragmentación ejecutando la recolección de noche.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Senior',
    'explicacion' => 'ZGC realiza casi todo el trabajo de forma concurrente con pausas < 1 ms.',
    'tema' => 'java',
  ),
  78 => 
  array (
    'pregunta' => '¿Cuál es la mejor práctica de arquitectura para resolver dependencias circulares?',
    'opcion_a' => 'Habilitar spring.main.allow-circular-references=true en producción.',
    'opcion_b' => 'Usar anotaciones @Lazy en todos los atributos de cada componente.',
    'opcion_c' => 'Refactorizar extrayendo la responsabilidad común a un tercer servicio.',
    'opcion_d' => 'Convertir los beans en clases abstractas con métodos estáticos.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Senior',
    'explicacion' => 'Extraer un servicio mediador o usar eventos elimina el acoplamiento cíclico.',
    'tema' => 'java',
  ),
  79 => 
  array (
    'pregunta' => '¿Qué controla el parámetro -XX:MaxDirectMemorySize en la JVM?',
    'opcion_a' => 'El tamaño máximo de memoria asignado a la pila de cada hilo.',
    'opcion_b' => 'La memoria reservada para el almacenamiento de código del JIT.',
    'opcion_c' => 'El espacio máximo del área Metaspace para metadatos de clases.',
    'opcion_d' => 'El límite de memoria fuera del Heap asignada vía NIO DirectByteBuffer.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'Limita la memoria off-heap que librerías como Netty usan para buffers directos.',
    'tema' => 'java',
  ),
  80 => 
  array (
    'pregunta' => '¿Cuál es la función principal de la anotación @CacheEvict en Spring Framework?',
    'opcion_a' => 'Eliminar una o múltiples entradas obsoletas de la memoria caché cuando se realizan operaciones de actualización o eliminación.',
    'opcion_b' => 'Deshabilitar de forma permanente el uso de caché en todos los controladores de la aplicación web.',
    'opcion_c' => 'Comprimir los datos del caché utilizando algoritmos gzip para reducir el consumo de memoria en disco.',
    'opcion_d' => 'Forzar la recarga síncrona de toda la base de datos en el arranque de la aplicación.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => '@CacheEvict limpia entradas específicas o todo el caché (allEntries = true) para asegurar consistencia ante escrituras.',
    'tema' => 'java',
  ),
  81 => 
  array (
    'pregunta' => '¿Qué anomalía de concurrencia previene el nivel de aislamiento SERIALIZABLE?',
    'opcion_a' => 'Solo lecturas sucias (Dirty Reads).',
    'opcion_b' => 'Lecturas fantasma, lecturas no repetibles y lecturas sucias.',
    'opcion_c' => 'Exclusivamente la pérdida de actualizaciones concurrentes.',
    'opcion_d' => 'Ninguna, solo optimiza la velocidad de las consultas SELECT.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Senior',
    'explicacion' => 'SERIALIZABLE es el nivel más estricto y previene lecturas fantasma (Phantom).',
    'tema' => 'java',
  ),
  82 => 
  array (
    'pregunta' => '¿Qué principio rige la delegación de carga en los ClassLoaders clásicos de Java?',
    'opcion_a' => 'Primero en entrar, primero en salir (FIFO) en memoria.',
    'opcion_b' => 'Carga directa en memoria sin consultar a ninguna clase previa.',
    'opcion_c' => 'Delegación hacia el ClassLoader padre antes de intentar cargar.',
    'opcion_d' => 'Inversión de dependencias basada exclusivamente en anotaciones.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Senior',
    'explicacion' => 'Un ClassLoader delega la búsqueda a su padre antes de buscar la clase él mismo.',
    'tema' => 'java',
  ),
  83 => 
  array (
    'pregunta' => '¿Qué tipo de ataque mitiga la inclusión de tokens CSRF en aplicaciones web?',
    'opcion_a' => 'Inyección de código SQL malicioso en formularios de búsqueda.',
    'opcion_b' => 'Ataques de denegación de servicio distribuido (DDoS) masivo.',
    'opcion_c' => 'Robo de contraseñas mediante fuerza bruta en el endpoint de login.',
    'opcion_d' => 'Peticiones no autorizadas enviadas desde un sitio externo de confianza.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'CSRF previene que un sitio malicioso ejecute acciones en nombre del usuario.',
    'tema' => 'java',
  ),
  84 => 
  array (
    'pregunta' => '¿Por qué LongAdder ofrece mejor rendimiento que AtomicLong bajo alta contención?',
    'opcion_a' => 'Distribuye la cuenta en celdas internas reduciendo colisiones de CAS.',
    'opcion_b' => 'Evita el uso de memoria RAM delegando los conteos a la tarjeta gráfica.',
    'opcion_c' => 'Utiliza bloqueos sincronizados a nivel de kernel del sistema operativo.',
    'opcion_d' => 'Descarta operaciones duplicadas mediante compresión de datos en memoria.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'LongAdder mantiene un arreglo de celdas que hilos concurrentes actualizan.',
    'tema' => 'java',
  ),
  85 => 
  array (
    'pregunta' => '¿Qué servidor embebido utiliza por defecto Spring WebFlux para I/O no bloqueante?',
    'opcion_a' => 'Apache Tomcat con hilos síncronos clásicos.',
    'opcion_b' => 'Reactor Netty basado en bucles de eventos no bloqueantes.',
    'opcion_c' => 'GlassFish Application Server.',
    'opcion_d' => 'Red Hat WildFly Server.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Senior',
    'explicacion' => 'WebFlux utiliza Reactor Netty con event-loops para alta concurrencia no bloqueante.',
    'tema' => 'java',
  ),
  86 => 
  array (
    'pregunta' => '¿En qué momento recolecta el GC los objetos apuntados por una SoftReference?',
    'opcion_a' => 'Inmediatamente en el siguiente ciclo de recolección menor.',
    'opcion_b' => 'Nunca son recolectados mientras la JVM permanezca encendida.',
    'opcion_c' => 'Solo cuando la JVM experimenta escasez crítica de memoria disponible.',
    'opcion_d' => 'Cuando el hilo que creó la referencia finaliza su ejecución.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Senior',
    'explicacion' => 'SoftReference se conserva hasta que la memoria es escasa (ideal para cachés).',
    'tema' => 'java',
  ),
  87 => 
  array (
    'pregunta' => '¿Qué técnica se utiliza con Testcontainers en pruebas de integración para Spring Boot?',
    'opcion_a' => 'Empaquetar todos los tests en un archivo ZIP para enviarlos a un servidor remoto de análisis estático, mediante la delegación de responsabilidades a proxies dinámicos y componentes gestionados.',
    'opcion_b' => 'Simular completamente el kernel del sistema operativo dentro del código fuente de la prueba unitaria, permitiendo el procesamiento asíncrono no bloqueante con alto rendimiento computacional.',
    'opcion_c' => 'Compilar la aplicación a código nativo antes de ejecutar las aserciones de JUnit, garantizando la seguridad de tipos y la coherencia en la memoria compartida de la JVM.',
    'opcion_d' => 'Levantar instancias reales y desechables de bases de datos o servicios (PostgreSQL, Kafka, Redis) en contenedores Docker durante la ejecución del test.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'Testcontainers permite ejecutar pruebas de integración fiables contra servicios reales empaquetados en contenedores Docker efímeros.',
    'tema' => 'java',
  ),
  88 => 
  array (
    'pregunta' => '¿En qué consiste el algoritmo Work-Stealing en el pool Fork/Join de Java?',
    'opcion_a' => 'Hilos desocupados roban tareas del final de la cola de hilos ocupados.',
    'opcion_b' => 'El hilo principal roba memoria de otros procesos del sistema operativo.',
    'opcion_c' => 'Las tareas pendientes se envían a un nodo externo en la nube.',
    'opcion_d' => 'Cancela las tareas más lentas para priorizar las más rápidas.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Work-stealing maximiza el uso de CPU permitiendo robar subtareas pendientes.',
    'tema' => 'java',
  ),
  89 => 
  array (
    'pregunta' => '¿Cuál es el beneficio de integrar Flyway o Liquibase en proyectos Spring Boot?',
    'opcion_a' => 'Generar controladores REST a partir de esquemas de bases de datos.',
    'opcion_b' => 'Versionar y aplicar migraciones de esquema de base de datos ordenadamente.',
    'opcion_c' => 'Reemplazar el uso de drivers JDBC por conexiones directas de red.',
    'opcion_d' => 'Monitorear el rendimiento de consultas lentas en tiempo real.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Senior',
    'explicacion' => 'Garantiza migraciones reproducibles y versionadas entre distintos ambientes.',
    'tema' => 'java',
  ),
  90 => 
  array (
    'pregunta' => '¿Qué optimización de compilación realiza el compilador JIT conocida como "Method Inlining"?',
    'opcion_a' => 'Mueve los métodos estáticos a un espacio de memoria fuera del proceso de la máquina virtual de Java.',
    'opcion_b' => 'Convierte todas las clases abstractas en interfaces para acelerar la resolución de enlaces dinámicos en tiempo de ejecución.',
    'opcion_c' => 'Reemplaza la llamada a un método pequeño por el cuerpo del código del método directamente en el sitio de invocación, eliminando sobrecostes de pila.',
    'opcion_d' => 'Elimina las comprobaciones de tipos de datos en tiempo de compilación para generar archivos ejecutables más pequeños.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Senior',
    'explicacion' => 'Method Inlining elimina el overhead de frame de llamada en stack y habilita subsecuentes optimizaciones como dead code elimination y constant folding.',
    'tema' => 'java',
  ),
  91 => 
  array (
    'pregunta' => '¿Qué ventaja ofrece usar ApplicationEventPublisher para la comunicación interna?',
    'opcion_a' => 'Reemplaza el uso de HTTP para comunicación externa con clientes.',
    'opcion_b' => 'Elimina la necesidad de utilizar bases de datos relacionales.',
    'opcion_c' => 'Obliga a que todos los métodos se ejecuten de forma asíncrona.',
    'opcion_d' => 'Desacopla componentes emisores de receptores mediante publicación de eventos.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'Promueve bajo acoplamiento al emitir eventos sin conocer a los listeners.',
    'tema' => 'java',
  ),
  92 => 
  array (
    'pregunta' => '¿Por qué se prefiere el patrón Saga sobre 2PC en arquitecturas de microservicios?',
    'opcion_a' => 'Evita bloqueos síncronos distribuidos mediante transacciones compensatorias.',
    'opcion_b' => 'Permite usar SQL en bases de datos NoSQL sin configuración adicional.',
    'opcion_c' => 'Garantiza consistencia estricta instantánea en toda la red.',
    'opcion_d' => 'Reduce el costo de almacenamiento en discos SSD del servidor.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Saga divide la transacción en pasos locales con acciones compensatorias si falla.',
    'tema' => 'java',
  ),
  93 => 
  array (
    'pregunta' => '¿Cómo funciona el mecanismo de Dirty Checking en Hibernate?',
    'opcion_a' => 'Escanea tablas en segundo plano para borrar registros obsoletos.',
    'opcion_b' => 'Compara el estado actual con la instantánea original para emitir UPDATEs.',
    'opcion_c' => 'Verifica sintaxis SQL antes de enviar sentencias a la base de datos.',
    'opcion_d' => 'Limpia la memoria del pool de conexiones tras cada petición web.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Senior',
    'explicacion' => 'Hibernate detecta cambios comparando con el snapshot al hacer flush.',
    'tema' => 'java',
  ),
  94 => 
  array (
    'pregunta' => '¿Qué efecto tiene activar el flag -XX:+UseStringDeduplication en la JVM?',
    'opcion_a' => 'Impide registrar usuarios con nombres duplicados en formularios.',
    'opcion_b' => 'Elimina cadenas repetidas en archivos de log en disco duro.',
    'opcion_c' => 'Hace que cadenas String idénticas compartan el mismo arreglo de bytes.',
    'opcion_d' => 'Convierte todas las cadenas a formato minúsculas en el heap.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Senior',
    'explicacion' => 'Reduce el uso de memoria haciendo que cadenas iguales compartan char[]/byte[].',
    'tema' => 'java',
  ),
  95 => 
  array (
    'pregunta' => '¿Qué optimización aporta @Transactional(readOnly = true) con Hibernate?',
    'opcion_a' => 'Bloquea el motor impidiendo escrituras de cualquier otra sesión.',
    'opcion_b' => 'Envía consultas exclusivamente a réplicas de lectura de la base.',
    'opcion_c' => 'Desactiva la necesidad de abrir transacciones JDBC con el driver.',
    'opcion_d' => 'Evita guardar snapshots para Dirty Checking reduciendo consumo de CPU.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'Al desactivar dirty checking y flushes innecesarios, ahorra memoria y cómputo.',
    'tema' => 'java',
  ),
  96 => 
  array (
    'pregunta' => '¿Qué es el fenómeno de False Sharing en arquitecturas multiprocesador en Java?',
    'opcion_a' => 'Hilos en núcleos distintos invalidan cachés al modificar la misma línea.',
    'opcion_b' => 'Dos procesos comparten el mismo puerto TCP causando conflicto de red.',
    'opcion_c' => 'Variables estáticas son sobrescritas por librerías externas en la JVM.',
    'opcion_d' => 'El recolector de basura suspende hilos que no tienen referencias activas.',
    'respuesta_correcta' => 'A',
    'complejidad' => 'Senior',
    'explicacion' => 'Ocurre cuando variables distintas residen en la misma línea de caché (64 bytes).',
    'tema' => 'java',
  ),
  97 => 
  array (
    'pregunta' => '¿Cuál es el beneficio de compilar una aplicación Java con GraalVM Native Image?',
    'opcion_a' => 'Permite ejecutar la aplicación sin compilar el código fuente.',
    'opcion_b' => 'Arranque casi instantáneo y menor consumo de memoria RAM sin JIT.',
    'opcion_c' => 'Compatibilidad total con reflection sin necesidad de configuración.',
    'opcion_d' => 'Permite modificar el código en caliente sin detener el contenedor.',
    'respuesta_correcta' => 'B',
    'complejidad' => 'Senior',
    'explicacion' => 'La compilación AOT genera binarios ultrarrápidos ideales para Serverless.',
    'tema' => 'java',
  ),
  98 => 
  array (
    'pregunta' => '¿Por qué se especifica rollbackFor = Exception.class en @Transactional?',
    'opcion_a' => 'Para forzar el reinicio del servidor web ante cualquier excepción.',
    'opcion_b' => 'Para ignorar excepciones no verificadas y confirmar los cambios.',
    'opcion_c' => 'Para revertir la transacción también ante excepciones verificadas (checked).',
    'opcion_d' => 'Para registrar errores en un archivo de bitácora independiente en disco.',
    'respuesta_correcta' => 'C',
    'complejidad' => 'Senior',
    'explicacion' => 'Por defecto Spring solo revierte ante RuntimeException y Error, no checked.',
    'tema' => 'java',
  ),
  99 => 
  array (
    'pregunta' => '¿Cómo funciona la instrucción atómica Compare-And-Swap (CAS) en Java?',
    'opcion_a' => 'Bloquea todos los hilos del sistema operativo mientras actualiza.',
    'opcion_b' => 'Compara dos objetos y elimina el más antiguo para liberar memoria.',
    'opcion_c' => 'Copia el valor en disco duro antes de actualizar la variable en RAM.',
    'opcion_d' => 'Actualiza el valor en memoria solo si coincide con el valor esperado.',
    'respuesta_correcta' => 'D',
    'complejidad' => 'Senior',
    'explicacion' => 'CAS actualiza a nivel de CPU sin bloqueos si el valor actual coincide.',
    'tema' => 'java',
  ),
);
}
